/**
 * Chữ của giao diện mới, ba ngôn ngữ như prototype: Tiếng Việt (mặc định), English, Filipino.
 *
 * Đây là lớp DỰ PHÒNG. Khóa nào máy chủ `/i18n` đã có thì lấy của máy chủ (xem `useChu`),
 * khóa nào chưa có thì lấy ở đây — nhờ vậy màn hình không bao giờ trống chữ và vẫn đổi
 * được ngôn ngữ ngay cả khi chưa đăng nhập hoặc mất mạng.
 */
export type MaNgonNgu = "vi" | "en" | "fil";
export const NGON_NGU: Array<{ id: MaNgonNgu; ten: string }> = [
  { id: "vi", ten: "Tiếng Việt" },
  { id: "en", ten: "English" },
  { id: "fil", ten: "Filipino" },
];
const vi: Record<string, string> = {
  // chung
  on: "Bật", off: "Tắt", "common.on": "Bật", "common.off": "Tắt",
  understood: "Đã hiểu", cancel: "Huỷ", close: "Đóng", back: "Quay lại",
  loading: "Đang tải…", working: "Đang kết nối…",
  // nav
  nav_home: "Nhà", nav_devices: "Thiết bị", nav_automation: "Tự động", nav_services: "Dịch vụ", nav_discover: "Khám phá",
  // home / devices
  all_houses: "Tất cả nhà", all_rooms: "Tất cả phòng",
  add_device: "Thêm thiết bị", pick_room: "Chọn phòng",
  no_device: "Chưa có thiết bị nào",
  no_device_hint: "Thêm thiết bị hoặc đổi bộ lọc để xem danh sách.",
  unassigned_room: "Chưa gán phòng",
  offline: "Ngoại tuyến",
  // automation
  auto_if: "Nếu–Thì", auto_time: "Theo thời gian",
  auto_empty: "Chưa có tự động hoá nào.<br>Nếu–Thì: nóng hơn 30°C thì bật quạt. Theo thời gian: chia nhiều chặng, mỗi chặng làm một việc.",
  if_label: "Nếu", then_label: "Thì",
  auto_run: "Chạy ngay", auto_delete: "Xoá",
  auto_from_device: "Từ thiết bị",
  auto_from_device_hint: "Chương trình hẹn giờ của thiết bị — sửa ở màn thiết bị.",
  shadow_tag: "chạy thử",
  // services
  svc_maintenance: "Bảo dưỡng", svc_warranty: "BH chính hãng",
  svc_activate: "Kích hoạt bảo hành", svc_shop: "Mua hàng",
  // discover
  dh_title: "Khám phá Livotec.com",
  dh_sub: "Xem toàn bộ sản phẩm, tin công nghệ và ưu đãi mới nhất tại website chính thức",
  dh_btn: "Mở trang web",
  // menu
  menu_title: "Menu",
  menu_spaces: "Quản lý Nhà / Phòng / Nhóm",
  menu_members: "Thành viên & chia sẻ",
  menu_devices: "Thiết bị",
  menu_add: "Thêm thiết bị / Setup WiFi",
  menu_virtual: "Thiết bị ảo",
  logout: "Đăng xuất",
  version_line: "Livotec Aiotec Smart · {ban}",
  // profile
  // notif
  notif_title: "Thông báo", notif_empty: "Không có thông báo", notif_clear: "Xoá hết",
  // login
  login_welcome: "Chào mừng",
  login_back: "bạn trở lại",
  login_sub: "Livotec, đem lại cuộc sống vui - khỏe mọi lúc, mọi nơi",
  login_user: "Tên đăng nhập hoặc email",
  login_email: "Email",
  login_name: "Họ và tên",
  login_pass: "Mật khẩu",
  login_btn: "Đăng nhập",
  login_signup: "Tạo tài khoản",
  login_face_hint: "hoặc quét khuôn mặt (mô phỏng)",
  login_create: "Tạo tài khoản mới",
  login_scanning: "Đang nhận diện khuôn mặt…",
  login_face_demo: "Quét khuôn mặt chưa có ở máy chủ — đây là bản mô phỏng, hãy nhập mật khẩu để vào.",
  login_need_all: "Vui lòng nhập đầy đủ tài khoản và mật khẩu.",
  login_bad: "Tài khoản hoặc mật khẩu không đúng.",
  // device detail
  // add device
  // placeholder
  placeholder_msg: "Tính năng này sẽ mở màn hình riêng trong bản chính thức.",
  // aircon
 ac_room_temp: "Nhiệt độ phòng",
  save: "Lưu",
  rule_conds: "{n} điều kiện", rule_gates: "{n} chỉ khi", rule_excl: "{n} trừ khi", rule_actions: "{n} hành động",
  rule_history: "Lịch sử chạy", rule_history_empty: "Chưa chạy lần nào.",
  rule_history_mock: "Lịch sử chạy do máy chủ giữ — chế độ mock chưa có.",
  rule_stop: "Dừng chương trình",
  hg_title: "Hẹn giờ thiết bị", hg_open: "Hẹn giờ",
  hg_mock: "Hẹn giờ do máy chủ IoTX giữ. Ứng dụng đang chạy ở chế độ mock nên màn này chưa dùng được.",
  hg_unsupported: "Sản phẩm này không hỗ trợ hẹn giờ.",
  hg_one_shot: "Hẹn bật / tắt", hg_none: "Chưa đặt hẹn nào.",
  hg_will_on: "Sẽ bật", hg_will_off: "Sẽ tắt", hg_cancel: "Huỷ hẹn",
  hg_then_on: "Tới giờ thì bật", hg_then_off: "Tới giờ thì tắt",
  hg_at_time: "Vào lúc", hg_after: "Sau bao lâu", hg_at: "Giờ", hg_minutes: "Số phút ({min}–{max})",
  hg_set: "Đặt hẹn", hg_replace_note: "Mỗi thiết bị chỉ giữ một hẹn — đặt cái mới là thay cái cũ.",
  hg_programs: "Chương trình", hg_no_program: "Chưa có chương trình nào.",
  hg_new_program: "Tạo chương trình", hg_edit_program: "Sửa chương trình",
  hg_in_use: "đang dùng", hg_use: "Dùng", hg_unuse: "Thôi dùng",
  hg_running: "Chương trình đang chạy, xong {n} bước.",
  hg_revoked: "{n} chức năng đã bị thu hồi",
  hg_program_name: "Tên chương trình",
  hg_kind: "Mốc tính theo", hg_kind_gio: "Giờ trong ngày", hg_kind_khoang: "Phút kể từ lúc bắt đầu",
  hg_run: "Cách chạy", hg_run_once: "Một lần", hg_run_repeat: "Lặp lại",
  hg_start: "Giờ bắt đầu chu kỳ",
  hg_steps: "Các bước", hg_steps_n: "{n} bước", hg_step_n: "Bước {n}",
  hg_minute: "Phút thứ", hg_capability: "Chức năng", hg_value: "Giá trị",
  hg_add_action: "Thêm hành động", hg_del_action: "Bớt hành động", hg_add_step: "Thêm bước",
  hg_invalid: "Cần tên, ít nhất một bước có hành động, và chọn ngày nếu lặp lại.",
  hg_no_cap: "Sản phẩm này chưa khai chức năng nào được phép đặt trong bước.",
  hg_loi_ten: "Chương trình cần có tên.",
  hg_loi_hd: "Bước {n} chưa có hành động nào.",
  hg_loi_cap: "Bước {n} dùng chức năng không còn được phép — chọn lại.",
  hg_loi_trung: "Bước {n} trùng giờ với một bước trước đó.",
  hg_loi_tang: "Bước {n} phải muộn hơn bước trước.",
  hg_loi_moc: "Bước {n}: phút phải nằm trong 1–1440.",
  hg_loi_ngay: "Lặp lại thì phải chọn ít nhất một ngày.",
  hg_loi_batdau: "Chu kỳ theo khoảng cần giờ bắt đầu.",
  pick_device: "Chọn thiết bị",
  supplies: "Vật tư",
  supplies_empty: "Chưa theo dõi vật tư nào.",
  supplies_add: "Thêm vật tư",
  supplies_add_hint: "Có serial chính hãng thì nhập serial để được xác thực; không có thì đặt tên tự do.",
  supplies_name: "Tên vật tư",
  supplies_serial: "Serial chính hãng (nếu có)",
  supplies_replace: "Thay",
  supplies_life: "Tuổi thọ {ngay} ngày",
  supplies_life_edit: "Sửa tuổi thọ",
  supplies_drop: "Bỏ",
  supplies_drop_confirm: "Bỏ theo dõi?",
  supplies_unverified: "chưa xác thực", next: "Sau",
  hide_device: "Ẩn thiết bị khỏi danh sách",
};
const en: Record<string, string> = {
  on: "On", off: "Off", "common.on": "On", "common.off": "Off",
  understood: "Got it", cancel: "Cancel", close: "Close", back: "Back",
  loading: "Loading…", working: "Connecting…",
  nav_home: "Home", nav_devices: "Devices", nav_automation: "Automation", nav_services: "Services", nav_discover: "Discover",
  all_houses: "All homes", all_rooms: "All rooms",
  add_device: "Add device", pick_room: "Pick a room",
  no_device: "No devices yet",
  no_device_hint: "Add a device or change the filters.",
  unassigned_room: "No room assigned",
  offline: "Offline",
  auto_if: "If–Then", auto_time: "Schedule",
  auto_empty: "No automation yet.<br>If–Then: hotter than 30°C turns the fan on. Schedule: several stages, one action each.",
  if_label: "If", then_label: "Then",
  auto_run: "Run now", auto_delete: "Delete",
  auto_from_device: "From devices",
  auto_from_device_hint: "Device timer programs — edit them on the device screen.",
  shadow_tag: "shadow",
  svc_maintenance: "Maintenance", svc_warranty: "Official warranty",
  svc_activate: "Activate warranty", svc_shop: "Shop",
  dh_title: "Discover Livotec.com",
  dh_sub: "Browse the full catalogue, tech news and the latest offers on the official site",
  dh_btn: "Open website",
  menu_title: "Menu",
  menu_spaces: "Homes / Rooms / Groups",
  menu_members: "Members & sharing",
  menu_devices: "Devices",
  menu_add: "Add device / Wi-Fi setup",
  menu_virtual: "Virtual devices",
  logout: "Sign out",
  version_line: "Livotec Aiotec Smart · {ban}",
  notif_title: "Notifications", notif_empty: "No notifications", notif_clear: "Clear all",
  login_welcome: "Welcome",
  login_back: "back",
  login_sub: "Livotec — a happier, healthier life anywhere",
  login_user: "Username or email",
  login_email: "Email",
  login_name: "Full name",
  login_pass: "Password",
  login_btn: "Sign in",
  login_signup: "Create account",
  login_face_hint: "or face scan (simulated)",
  login_create: "Create a new account",
  login_scanning: "Recognising your face…",
  login_face_demo: "Face sign-in is not available on the server yet — this is a simulation, please type your password.",
  login_need_all: "Please fill in both account and password.",
  login_bad: "Wrong account or password.",
  placeholder_msg: "This feature gets its own screen in the release build.", ac_room_temp: "Room Temperature",
  save: "Save",
  rule_conds: "{n} conditions", rule_gates: "{n} only when", rule_excl: "{n} except when", rule_actions: "{n} actions",
  rule_history: "Run history", rule_history_empty: "Never run yet.",
  rule_history_mock: "Run history lives on the server — not available in mock mode.",
  rule_stop: "Stop program",
  hg_title: "Device timers", hg_open: "Timers",
  hg_mock: "Timers live on the IoTX server. The app runs in mock mode, so this screen is unavailable.",
  hg_unsupported: "This product does not support timers.",
  hg_one_shot: "On / off timer", hg_none: "No timer set.",
  hg_will_on: "Will turn on", hg_will_off: "Will turn off", hg_cancel: "Cancel timer",
  hg_then_on: "Turn on", hg_then_off: "Turn off",
  hg_at_time: "At a time", hg_after: "After a delay", hg_at: "Time", hg_minutes: "Minutes ({min}–{max})",
  hg_set: "Set timer", hg_replace_note: "One timer per device — a new one replaces the old.",
  hg_programs: "Programs", hg_no_program: "No programs yet.",
  hg_new_program: "New program", hg_edit_program: "Edit program",
  hg_in_use: "in use", hg_use: "Use", hg_unuse: "Stop using",
  hg_running: "Program running, {n} steps done.",
  hg_revoked: "{n} capabilities revoked",
  hg_program_name: "Program name",
  hg_kind: "Steps measured by", hg_kind_gio: "Clock time", hg_kind_khoang: "Minutes from start",
  hg_run: "Run", hg_run_once: "Once", hg_run_repeat: "Repeat",
  hg_start: "Cycle start time",
  hg_steps: "Steps", hg_steps_n: "{n} steps", hg_step_n: "Step {n}",
  hg_minute: "Minute", hg_capability: "Capability", hg_value: "Value",
  hg_add_action: "Add action", hg_del_action: "Remove action", hg_add_step: "Add step",
  hg_invalid: "Needs a name, at least one step with an action, and days if repeating.",
  hg_no_cap: "This product declares no capability allowed inside a step.",
  hg_loi_ten: "The program needs a name.",
  hg_loi_hd: "Step {n} has no action yet.",
  hg_loi_cap: "Step {n} uses a capability that is no longer allowed — pick another.",
  hg_loi_trung: "Step {n} repeats a time an earlier step already uses.",
  hg_loi_tang: "Step {n} must come later than the step before it.",
  hg_loi_moc: "Step {n}: the minute must be between 1 and 1440.",
  hg_loi_ngay: "Repeating programs need at least one day.",
  hg_loi_batdau: "An interval cycle needs a start time.",
  pick_device: "Pick a device",
  supplies: "Consumables",
  supplies_empty: "Nothing tracked yet.",
  supplies_add: "Add consumable",
  supplies_add_hint: "Enter an official serial to get it verified, or just give it a name.",
  supplies_name: "Name",
  supplies_serial: "Official serial (optional)",
  supplies_replace: "Replace",
  supplies_life: "Life {ngay} days",
  supplies_life_edit: "Edit life",
  supplies_drop: "Drop",
  supplies_drop_confirm: "Stop tracking?",
  supplies_unverified: "unverified", next: "Next",
  hide_device: "Hide this device from the list",
};
const fil: Record<string, string> = {
  on: "On", off: "Off", "common.on": "On", "common.off": "Off",
  understood: "Naiintindihan", cancel: "Kanselahin", close: "Isara", back: "Bumalik",
  loading: "Naglo-load…", working: "Kumokonekta…",
  nav_home: "Tahanan", nav_devices: "Device", nav_automation: "Automation", nav_services: "Serbisyo", nav_discover: "Tuklasin",
  all_houses: "Lahat ng tahanan", all_rooms: "Lahat ng silid",
  add_device: "Magdagdag ng device", pick_room: "Pumili ng silid",
  no_device: "Wala pang device",
  no_device_hint: "Magdagdag ng device o baguhin ang filter.",
  unassigned_room: "Wala pang silid",
  offline: "Offline",
  auto_if: "Kung–Kaya", auto_time: "Ayon sa oras",
  auto_empty: "Wala pang automation.<br>Kung–Kaya: kapag lumampas sa 30°C, buksan ang fan. Ayon sa oras: hatiin sa mga yugto.",
  if_label: "Kung", then_label: "Kaya",
  auto_run: "Patakbuhin", auto_delete: "Tanggalin",
  auto_from_device: "Mula sa device",
  auto_from_device_hint: "Timer program ng device — i-edit sa screen ng device.",
  shadow_tag: "pagsubok",
  svc_maintenance: "Maintenance", svc_warranty: "Opisyal na warranty",
  svc_activate: "I-activate ang warranty", svc_shop: "Mamili",
  dh_title: "Tuklasin ang Livotec.com",
  dh_sub: "Tingnan ang lahat ng produkto, balita at pinakabagong alok sa opisyal na website",
  dh_btn: "Buksan ang website",
  menu_title: "Menu",
  menu_spaces: "Tahanan / Silid / Grupo",
  menu_members: "Miyembro at pagbabahagi",
  menu_devices: "Device",
  menu_add: "Magdagdag ng device / Wi-Fi setup",
  menu_virtual: "Virtual na device",
  logout: "Mag-sign out",
  version_line: "Livotec Aiotec Smart · {ban}",
  notif_title: "Mga abiso", notif_empty: "Walang abiso", notif_clear: "Burahin lahat",
  login_welcome: "Maligayang pagdating",
  login_back: "muli",
  login_sub: "Livotec — masaya at malusog na buhay saan man",
  login_user: "Username o email",
  login_email: "Email",
  login_name: "Buong pangalan",
  login_pass: "Password",
  login_btn: "Mag-sign in",
  login_signup: "Gumawa ng account",
  login_face_hint: "o face scan (simulasyon)",
  login_create: "Gumawa ng bagong account",
  login_scanning: "Kinikilala ang mukha…",
  login_face_demo: "Wala pang face sign-in sa server — simulasyon ito, i-type ang password.",
  login_need_all: "Punan ang account at password.",
  login_bad: "Mali ang account o password.",
  placeholder_msg: "May sariling screen ang feature na ito sa release build.", ac_room_temp: "Temperatura ng Silid",
  save: "I-save",
  rule_conds: "{n} kondisyon", rule_gates: "{n} kung", rule_excl: "{n} maliban", rule_actions: "{n} aksyon",
  rule_history: "Kasaysayan ng pagtakbo", rule_history_empty: "Hindi pa tumatakbo.",
  rule_history_mock: "Nasa server ang kasaysayan — wala sa mock mode.",
  rule_stop: "Itigil ang programa",
  hg_title: "Timer ng device", hg_open: "Timer",
  hg_mock: "Nasa IoTX server ang timer. Mock mode ang app kaya hindi pa magagamit ito.",
  hg_unsupported: "Hindi sinusuportahan ng produktong ito ang timer.",
  hg_one_shot: "On / off timer", hg_none: "Walang nakatakdang timer.",
  hg_will_on: "Bubuksan", hg_will_off: "Isasara", hg_cancel: "Kanselahin",
  hg_then_on: "Buksan", hg_then_off: "Isara",
  hg_at_time: "Sa oras", hg_after: "Pagkalipas ng", hg_at: "Oras", hg_minutes: "Minuto ({min}–{max})",
  hg_set: "Itakda", hg_replace_note: "Isang timer bawat device — papalitan ang luma.",
  hg_programs: "Mga programa", hg_no_program: "Wala pang programa.",
  hg_new_program: "Bagong programa", hg_edit_program: "I-edit ang programa",
  hg_in_use: "ginagamit", hg_use: "Gamitin", hg_unuse: "Itigil",
  hg_running: "Tumatakbo, {n} hakbang na ang tapos.",
  hg_revoked: "{n} kakayahan ang binawi",
  hg_program_name: "Pangalan ng programa",
  hg_kind: "Batayan ng hakbang", hg_kind_gio: "Oras sa araw", hg_kind_khoang: "Minuto mula sa simula",
  hg_run: "Pagtakbo", hg_run_once: "Isang beses", hg_run_repeat: "Ulitin",
  hg_start: "Oras ng simula",
  hg_steps: "Mga hakbang", hg_steps_n: "{n} hakbang", hg_step_n: "Hakbang {n}",
  hg_minute: "Minuto", hg_capability: "Kakayahan", hg_value: "Halaga",
  hg_add_action: "Magdagdag ng aksyon", hg_del_action: "Bawasan", hg_add_step: "Magdagdag ng hakbang",
  hg_invalid: "Kailangan ng pangalan, kahit isang hakbang na may aksyon, at araw kung uulitin.",
  hg_no_cap: "Walang kakayahang pinapayagan sa hakbang ang produktong ito.",
  hg_loi_ten: "Kailangan ng pangalan ang programa.",
  hg_loi_hd: "Wala pang aksyon ang hakbang {n}.",
  hg_loi_cap: "Gumagamit ang hakbang {n} ng kakayahang hindi na pinapayagan — pumili ng iba.",
  hg_loi_trung: "Kapareho ng oras ng naunang hakbang ang hakbang {n}.",
  hg_loi_tang: "Dapat mas huli ang hakbang {n} kaysa sa naunang hakbang.",
  hg_loi_moc: "Hakbang {n}: dapat nasa 1–1440 ang minuto.",
  hg_loi_ngay: "Kailangan ng kahit isang araw kapag paulit-ulit.",
  hg_loi_batdau: "Kailangan ng oras ng simula ang siklong panagitan.",
  pick_device: "Pumili ng device",
  supplies: "Consumables",
  supplies_empty: "Wala pang sinusubaybayan.",
  supplies_add: "Magdagdag",
  supplies_add_hint: "Maglagay ng opisyal na serial para ma-verify, o pangalan na lang.",
  supplies_name: "Pangalan",
  supplies_serial: "Opisyal na serial (opsyonal)",
  supplies_replace: "Palitan",
  supplies_life: "Buhay {ngay} araw",
  supplies_life_edit: "Baguhin ang buhay",
  supplies_drop: "Alisin",
  supplies_drop_confirm: "Itigil ang pagsubaybay?",
  supplies_unverified: "hindi verified", next: "Susunod",
  hide_device: "Itago ang device sa listahan",
};
/* ------------------------------------------------------------------ */
/* Chữ của tám màn thiết bị mới (bản giao diện MasterDetail)            */
/* ------------------------------------------------------------------ */
const MOI: Record<MaNgonNgu, Record<string, string>> = {
  vi: {
    online: "Đang kết nối",
    close: "Đóng",
    khung_more: "Xem thêm",
    khung_less: "Thu gọn",
    khong_co_khuon: "Sản phẩm này chưa được khai khuôn giao diện, nên chưa dựng được màn điều khiển.",
    hg_chua_dat: "chưa đặt gì — chạm để cài",
    hg_ghim_bat: "sẽ BẬT lúc {luc}",
    hg_ghim_tat: "sẽ TẮT lúc {luc}",
    hg_ghim_chay: "đang chạy “{ten}” — xong {n} bước",
    hg_ghim_dung: "đang dùng “{ten}”",
    nhac_offline: "Thiết bị đang ngoại tuyến — lệnh vẫn gửi được nhưng có thể chưa tới ngay.",
    chan_khongQuyen: "Bạn chỉ được xem thiết bị này. Nhờ chủ nhà cấp quyền điều khiển trong mục Thành viên.",
    chan_khong_lenh: "Catalog chưa khai lệnh cho “{ten}”, nên mục này chỉ để xem.",
    device: "Thiết bị",
    // bộ lọc nhà / nhóm
    pick_house: "Chọn nhà", pick_group: "Chọn nhóm", all_groups: "Tất cả nhóm",
    nhom_lam_mat: "Làm mát", nhom_bep: "Nhà bếp", nhom_nuoc: "Nước", nhom_khac: "Khác",
    // bếp từ
    // hút mùi
    // lọc nước
    // bình nóng lạnh
    // nồi cơm
    // quạt
  },
  en: {
    online: "Online",
    close: "Close",
    khung_more: "Show more",
    khung_less: "Show less",
    khong_co_khuon: "This product has no UI archetype declared, so no control screen can be built.",
    hg_chua_dat: "nothing set yet — tap to configure",
    hg_ghim_bat: "will turn ON at {luc}",
    hg_ghim_tat: "will turn OFF at {luc}",
    hg_ghim_chay: "running “{ten}” — {n} steps done",
    hg_ghim_dung: "using “{ten}”",
    nhac_offline: "The device is offline — commands still go out, but may not arrive right away.",
    chan_khongQuyen: "You only have view access. Ask the home owner for control rights under Members.",
    chan_khong_lenh: "The catalogue declares no command for “{ten}”, so it is view-only.",
    device: "Device",
    pick_house: "Pick a home", pick_group: "Pick a group", all_groups: "All groups",
    nhom_lam_mat: "Cooling", nhom_bep: "Kitchen", nhom_nuoc: "Water", nhom_khac: "Other",
  },
  fil: {
    online: "Online",
    close: "Isara",
    khung_more: "Magpakita pa",
    khung_less: "Bawasan",
    khong_co_khuon: "Walang naideklarang UI archetype ang produktong ito, kaya walang control screen.",
    hg_chua_dat: "wala pang naka-set — pindutin para i-configure",
    hg_ghim_bat: "bubukas sa {luc}",
    hg_ghim_tat: "magsasara sa {luc}",
    hg_ghim_chay: "tumatakbo ang “{ten}” — {n} hakbang na tapos",
    hg_ghim_dung: "ginagamit ang “{ten}”",
    nhac_offline: "Offline ang device — naipapadala pa rin ang utos, pero baka hindi agad dumating.",
    chan_khongQuyen: "Tingin lang ang access mo. Humingi ng control rights sa may-ari sa ilalim ng Members.",
    chan_khong_lenh: "Walang naidedeklarang utos ang catalogue para sa “{ten}”, kaya tingin lang ito.",
    device: "Device",
    pick_house: "Pumili ng bahay", pick_group: "Pumili ng grupo", all_groups: "Lahat ng grupo",
    nhom_lam_mat: "Palamig", nhom_bep: "Kusina", nhom_nuoc: "Tubig", nhom_khac: "Iba pa",
  },
};
/* ------------------------------------------------------------------ */
/* Chữ của các panel quản lý: tự động, thiết bị ảo, thành viên, không   */
/* gian, thêm thiết bị. Trước đây nằm rải rác làm tham số mặc định cho  */
/* `t()` của hệ i18n thứ hai; gom về đây để app chỉ còn MỘT bảng chữ.   */
/* Chỉ điền tiếng Việt: `useChu` rơi bậc en/fil về vi, đúng y như hành  */
/* vi cũ (tham số mặc định trước đây cũng là tiếng Việt).               */
/* ------------------------------------------------------------------ */
const PANEL: Record<MaNgonNgu, Record<string, string>> = {
  vi: {
    "routine.previewFailed": "không xem trước được",
    "routine.and": "VÀ",
    "routine.or": "HOẶC",
    "common.delete": "Xoá",
    "routine.timeWindow": "Khung giờ",
    "common.to": "đến",
    "routine.noDays": "Không chọn ngày nào = mọi ngày",
    "routine.pickDevice": "Chọn thiết bị",
    "routine.pickCap": "Chọn chỉ số",
    "common.add": "Thêm",
    "common.back": "Quay lại",
    "routine.condTitle": "Tự động Nếu–Thì",
    "routine.title": "Tự động",
    "routine.namePhCond": "Tên, vd. Nóng thì bật quạt",
    "routine.if": "NẾU",
    "routine.allConds": "Phải đúng tất cả thì mới chạy.",
    "routine.onlyOpt": "CHỈ KHI (không bắt buộc)",
    "routine.onlyHint": "Rào cho phép — phải đúng hết thì mới chạy.",
    "routine.exceptOpt": "TRỪ KHI (không bắt buộc)",
    "routine.exceptHint": "Rào chặn — đúng một cái là không chạy.",
    "routine.thenMax": "THÌ (tối đa 20)",
    "routine.doWhat": "Làm gì",
    "routine.actionN": "hành động {n}",
    "routine.notifyDefault": "Tự động hoá vừa chạy",
    "common.device": "thiết bị",
    "routine.sendNotify": "Gửi thông báo",
    "routine.notifyText": "Nội dung thông báo",
    "routine.waitSeconds": "chờ (giây)",
    "routine.validityFull": "HIỆU LỰC (để trống = ngay và mãi mãi)",
    "routine.expiryHint": "Hết hạn thì tự động hoá tự tắt, không bị xoá.",
    "routine.hold": "Điều kiện phải đúng liên tục",
    "routine.holdNow": "ngay lập tức",
    "dur.30s": "30 giây",
    "dur.1m": "1 phút",
    "dur.5m": "5 phút",
    "routine.yield": "Nhường tay người dùng",
    "routine.noYield": "không nhường",
    "dur.15m": "15 phút",
    "dur.1h": "1 giờ",
    "routine.yieldHint": "Bạn vừa tự chỉnh thiết bị thì tự động hoá không đụng vào nó trong khoảng này.",
    "routine.preview": "Xem trước — bây giờ có chạy không?",
    "routine.willRun": "Ngay bây giờ sẽ chạy",
    "routine.wontRun": "Chưa chạy — {why}",
    "routine.pass": "đúng",
    "routine.fail": "sai",
    "routine.currently": "hiện {v}",
    "routine.shadowHint": "Tự động hoá mới luôn bắt đầu ở chế độ chạy thử: hệ ghi lại “lẽ ra đã chạy” nhưng chưa gửi lệnh thật.",
    "common.saving": "Đang lưu…",
    "common.save": "Lưu",
    "routine.value": "giá trị",
    "common.on": "Bật",
    "common.off": "Tắt",
    "virtual.external": "Nguồn ngoài",
    "virtual.externalDesc": "Thời tiết, chất lượng không khí",
    "virtual.phExternal": "Tên, vd. Thời tiết Hà Nội",
    "virtual.state": "Trạng thái nhà",
    "virtual.stateDesc": "Có người ở nhà, chế độ ngủ, đi vắng",
    "virtual.phState": "Tên, vd. Có người ở nhà",
    "virtual.button": "Nút bấm",
    "virtual.buttonDesc": "Về nhà, đi ngủ — bấm một cái là tự động hoá chạy",
    "virtual.phButton": "Tên, vd. Đi ngủ",
    "state.on": "Đang bật",
    "state.offNow": "Đang tắt",
    "virtual.pressCount": "đã bấm {n} lần",
    "virtual.humidity": "ẩm {v}%",
    "virtual.aqi": "không khí {v}",
    "virtual.noData": "chưa có dữ liệu — chờ lần lấy đầu tiên",
    "virtual.title": "Thiết bị ảo",
    "virtual.hint": "Thứ có tên và có trạng thái nhưng không phải máy móc trong nhà.",
    "common.create": "Tạo",
    "place.title": "Nơi",
    "virtual.pickPlace": "Chọn nơi",
    "virtual.limit": "Tối đa 10 thiết bị ảo. Cái nào đang được tự động hoá dùng thì không xoá được.",
    "common.close": "Đóng",
    "virtual.empty": "Chưa có thiết bị ảo nào.",
    "virtual.press": "Bấm",
    "share.viewOnly": "chỉ xem",
    "share.controlOnly": "chỉ điều khiển",
    "share.noDelete": "không được xóa",
    "share.fullAccess": "toàn quyền",
    "share.oneDevice": "một thiết bị",
    "share.needEmailHouse": "Nhập email và chọn nhà",
    "share.invited": "Đã mời — người này chưa có tài khoản, sẽ nhận khi đăng ký",
    "share.shared": "Đã chia sẻ ✓",
    "share.inviteFailed": "Không mời được — kiểm tra lại email",
    "share.permsUpdated": "Đã cập nhật quyền",
    "share.revoked": "Đã gỡ",
    "share.title": "Thành viên & chia sẻ",
    "share.invite": "Mời thành viên",
    "share.noHouse": "Bạn chưa có nhà nào để chia sẻ. Chỉ chủ nhà mới mời được thành viên — tạo nhà trong mục Quản lý Nhà / Phòng / Nhóm trước đã.",
    "share.emailPh": "Email người nhận",
    "share.scopeHouse": "Cả nhà",
    "share.scopeRoom": "Một phòng",
    "share.scopeDevice": "Một thiết bị",
    "share.pickHouse": "Chọn nhà",
    "share.pickRoom": "Chọn phòng",
    "share.defaultHint": "Mặc định thành viên dùng được mọi thứ như bạn. Siết bớt trong “Cài đặt nâng cao”.",
    "share.advanced": "Cài đặt nâng cao",
    "share.blockDelete": "Không cho xóa (vẫn tạo mới được)",
    "common.working": "Đang kết nối…",
    "share.doShare": "Chia sẻ",
    "share.sharedWith": "Đã chia sẻ cho",
    "share.noneShared": "Chưa chia sẻ cho ai.",
    "share.pending": "chờ đăng ký",
    "share.revokeConfirm": "Gỡ quyền truy cập của thành viên này?",
    "share.revoke": "Gỡ quyền",
    "share.sharedToMe": "Người khác chia sẻ cho tôi",
    "share.noneToMe": "Chưa có ai chia sẻ cho bạn.",
    "routine.condN": "điều kiện {n}",
    "share.oneRoom": "phòng {name}",
    "share.wholeHouse": "cả nhà {name}",
    "op.eq": "bằng",
    "op.neq": "khác",
    "op.gt": "lớn hơn",
    "op.lt": "nhỏ hơn",
    "dow.sun": "CN",
    "dow.mon": "T2",
    "dow.tue": "T3",
    "dow.wed": "T4",
    "dow.thu": "T5",
    "dow.fri": "T6",
    "dow.sat": "T7",
    notif_empty: "Chưa có thông báo nào.",
    notif_clear: "Xoá tất cả thông báo",
    auto_delete: "Xoá thông báo này",
    club_kitchen: "Hội Yêu Bếp",
    club_aircon: "Hội Điều Hòa",
    club_water: "Hội Máy Lọc Nước",
    club_fan: "Hội Quạt",
    promo_aircon: "Khuyến mãi điều hòa I-Boost",
    promo_wh: "Khuyến mãi bình nóng lạnh",
    loc_nha: "Nhà",
    loc_phong: "Phòng",
    loc_nhom: "Nhóm",
  },
  en: {},
  fil: {},
};
/** Khóa mới ghi đè khóa cũ cùng tên, để bản vá chữ không phải sửa ba khối lớn phía trên. */
export const CHU: Record<MaNgonNgu, Record<string, string>> = {
  vi: { ...vi, ...MOI.vi, ...PANEL.vi },
  en: { ...en, ...MOI.en, ...PANEL.en },
  fil: { ...fil, ...MOI.fil, ...PANEL.fil },
};
export function laMaNgonNgu(ma: string): ma is MaNgonNgu {
  return ma === "vi" || ma === "en" || ma === "fil";
}
