/**
 * Chữ của giao diện mới, ba ngôn ngữ như prototype: Tiếng Việt (mặc định), English, Filipino.
 *
 * Đây là lớp DỰ PHÒNG. Khóa nào máy chủ `/i18n` đã có thì lấy của máy chủ (xem `useChu`),
 * khóa nào chưa có thì lấy ở đây — nhờ vậy màn hình không bao giờ trống chữ và vẫn đổi
 * được ngôn ngữ ngay cả khi chưa đăng nhập hoặc mất mạng.
 */
export type MaNgonNgu = "vi" | "en" | "fil";
const vi: Record<string, string> = {
  // chung
  on: "Bật", off: "Tắt", "common.on": "Bật", "common.off": "Tắt",
  understood: "Đã hiểu", cancel: "Huỷ", close: "Đóng", back: "Quay lại",
  pin: "Ghim", unpin: "Bỏ ghim", confirm_delete: "Xoá?",
  loading: "Đang tải…", working: "Đang kết nối…",
  // nav
  nav_home: "Nhà", nav_devices: "Thiết bị", nav_automation: "Tự động", nav_services: "Dịch vụ", nav_discover: "Khám phá",
  // home / devices
  all_houses: "Tất cả nhà", all_rooms: "Tất cả phòng",
  add_device: "Thêm thiết bị", pick_room: "Chọn phòng",
  no_device: "Chưa có thiết bị nào",
  no_device_hint: "Thêm thiết bị hoặc đổi bộ lọc để xem danh sách.",
  unassigned_room: "Chưa gán phòng",
  offline: "Ngoại tuyến",
  // automation
  auto_if: "Nếu–Thì", auto_time: "Theo thời gian",
  auto_quota_full: "Đã đủ {n} luật — xoá bớt một luật để tạo thêm.",
  auto_empty: "Chưa có tự động hoá nào.<br>Nếu–Thì: nóng hơn 30°C thì bật quạt. Theo thời gian: chia nhiều chặng, mỗi chặng làm một việc.",
  if_label: "Nếu", then_label: "Thì",
  auto_run: "Chạy ngay", auto_delete: "Xoá",
  auto_from_device: "Từ thiết bị",
  auto_from_device_hint: "Chương trình hẹn giờ của thiết bị — sửa ở màn thiết bị.",
  shadow_tag: "chạy thử",
  // services
  svc_maintenance: "Bảo dưỡng", svc_warranty: "BH chính hãng",
  svc_activate: "Kích hoạt bảo hành", svc_shop: "Mua hàng",
  // discover
  dh_title: "Khám phá Livotec.com",
  dh_sub: "Xem toàn bộ sản phẩm, tin công nghệ và ưu đãi mới nhất tại website chính thức",
  dh_btn: "Mở trang web",
  // menu
  menu_title: "Menu",
  menu_spaces: "Quản lý Nhà / Phòng / Nhóm",
  menu_members: "Thành viên & chia sẻ",
  menu_devices: "Thiết bị",
  menu_add: "Thêm thiết bị / Setup WiFi",
  menu_virtual: "Thiết bị ảo",
  logout: "Đăng xuất",
  version_line: "Livotec Aiotec Smart · {ban}",
  menu_tai_khoan: "Tài khoản",
  menu_doi_mk: "Đổi mật khẩu",
  menu_doi_ten: "Đổi tên",
  dt_ten: "Tên hiển thị",
  dt_ten_ph: "Nhập tên hiển thị",
  dt_loi_trong: "Vui lòng nhập tên",
  dt_loi_dai: "Tên tối đa {n} ký tự",
  dt_chua_bat: "Chưa đổi được tên — tính năng đang chờ bật.",
  anh_doi: "Đổi ảnh đại diện",
  anh_chon: "Chọn ảnh",
  anh_loi_kieu: "Vui lòng chọn một tệp ảnh",
  anh_chua_bat: "Chưa đổi được ảnh đại diện — tính năng đang chờ bật.",
  menu_ngon_ngu: "Ngôn ngữ",
  menu_giao_dien: "Giao diện",
  gd_toi: "Tối",
  gd_sang: "Sáng",
  gd_he_thong: "Theo hệ thống",
  menu_thong_bao: "Thông báo",
  menu_thong_bao_mo_ta: "Chấm báo chưa đọc trên chuông",
  chu_co: "Cỡ chữ",
  co_vua: "Vừa",
  co_lon: "Lớn",
  co_rat_lon: "Rất lớn",
  chu_xem_truoc: "Điều hoà phòng khách đang bật ở 26°C.",
  dmk_cu: "Mật khẩu hiện tại",
  dmk_cu_ph: "Nhập mật khẩu hiện tại",
  dmk_moi: "Mật khẩu mới",
  dmk_moi_ph: "Nhập mật khẩu mới (≥ 8 ký tự)",
  dmk_nhap_lai: "Nhập lại mật khẩu mới",
  dmk_loi_cu: "Vui lòng nhập mật khẩu hiện tại",
  dmk_loi_trung: "Mật khẩu mới phải khác mật khẩu hiện tại",
  dmk_chua_bat: "Chưa đổi được mật khẩu — tính năng đang chờ bật.",
  dmk_xong: "Đã đổi mật khẩu.",
  // profile
  // notif
  notif_title: "Thông báo", notif_empty: "Không có thông báo", notif_clear: "Xoá hết",
  // login
  login_btn: "Đăng nhập",
  dn_tai_khoan: "Tài khoản",
  dn_tai_khoan_ph: "Email hoặc số điện thoại",
  dn_pw: "Mật khẩu",
  dn_pw_ph: "Nhập mật khẩu (≥ 8 ký tự)",
  dn_hien: "Hiện mật khẩu",
  dn_an: "Ẩn mật khẩu",
  dn_ghi_nho: "Ghi nhớ đăng nhập",
  dn_quen: "Quên mật khẩu?",
  dn_chua_co: "Bạn chưa có tài khoản?",
  dn_dk_ngay: "Đăng ký ngay",
  dn_quay_lai: "Quay lại đăng nhập",
  dn_loi_id_trong: "Vui lòng nhập email hoặc số điện thoại",
  dn_loi_id_sai: "Email hoặc số điện thoại không hợp lệ",
  dn_loi_pw_trong: "Vui lòng nhập mật khẩu",
  qm_title: "Quên mật khẩu",
  qm_lead: "Nhập email hoặc số điện thoại bạn đã đăng ký. Chúng tôi sẽ gửi mã xác nhận để đặt lại mật khẩu.",
  qm_gui: "Gửi mã xác nhận",
  qm_chua_bat: "Chưa gửi được mã — tính năng đang chờ bật.",
  dn_hoac: "hoặc",
  dn_google: "Tiếp tục với Google",
  dn_google_chua_bat: "Chưa đăng nhập được bằng Google — tính năng đang chờ bật.",
  qm_da_gui: "Đã gửi mã xác nhận",
  qm_da_gui_lead: "Chúng tôi đã gửi mã 6 số tới {dich}. Mã có hiệu lực trong 10 phút.",
  qm_nhap_ma: "Nhập mã xác nhận",
  qm_khong_nhan: "Không nhận được mã?",
  qm_gui_lai: "Gửi lại",
  qm_da_nho: "Đã nhớ mật khẩu?",
  dk_title: "Tạo tài khoản",
  dk_lead: "Chỉ mất chưa đến một phút.",
  dk_ten: "Họ và tên",
  dk_ten_ph: "Nguyễn Văn A",
  dk_pw2: "Nhập lại mật khẩu",
  dk_btn: "Đăng ký",
  dk_da_co: "Đã có tài khoản?",
  dk_loi_ten: "Vui lòng nhập họ và tên",
  dk_loi_pw_ngan: "Mật khẩu tối thiểu {n} ký tự",
  dk_loi_pw2: "Hai mật khẩu không khớp",
  login_lang: "Ngôn ngữ",
  login_bad: "Tài khoản hoặc mật khẩu không đúng.",
  // device detail
  // add device
  // placeholder
  placeholder_msg: "Tính năng này sẽ mở màn hình riêng trong bản chính thức.",
  // aircon
 ac_room_temp: "Nhiệt độ phòng",
  save: "Lưu",
  rule_conds: "{n} điều kiện", rule_gates: "{n} chỉ khi", rule_excl: "{n} trừ khi", rule_actions: "{n} hành động",
  rule_history: "Lịch sử chạy", rule_history_empty: "Chưa chạy lần nào.",
  rule_history_mock: "Lịch sử chạy do máy chủ giữ — chế độ mock chưa có.",
  rule_stop: "Dừng chương trình",
  hg_title: "Hẹn giờ thiết bị", hg_open: "Hẹn giờ",
  hg_mock: "Hẹn giờ do máy chủ IoTX giữ. Ứng dụng đang chạy ở chế độ mock nên màn này chưa dùng được.",
  hg_unsupported: "Sản phẩm này không hỗ trợ hẹn giờ.",
  hg_one_shot: "Hẹn bật / tắt", hg_none: "Chưa đặt hẹn nào.",
  hg_will_on: "Sẽ bật", hg_will_off: "Sẽ tắt", hg_cancel: "Huỷ hẹn",
  hg_then_on: "Tới giờ thì bật", hg_then_off: "Tới giờ thì tắt",
  hg_at_time: "Vào lúc", hg_after: "Sau bao lâu", hg_at: "Giờ", hg_minutes: "Số phút ({min}–{max})",
  hg_set: "Đặt hẹn", hg_replace_note: "Mỗi thiết bị chỉ giữ một hẹn — đặt cái mới là thay cái cũ.",
  hg_programs: "Chương trình", hg_no_program: "Chưa có chương trình nào.",
  hg_new_program: "Tạo chương trình", hg_edit_program: "Sửa chương trình",
  hg_xoa_that: "Xoá thật?", hg_khoa_sua: "Đang chạy giữa chừng — thôi dùng rồi hãy sửa.",
  hg_in_use: "đang dùng", hg_use: "Dùng", hg_unuse: "Thôi dùng",
  hg_running: "Chương trình đang chạy, xong {n} bước.",
  hg_revoked: "{n} chức năng đã bị thu hồi",
  hg_program_name: "Tên chương trình",
  hg_kind: "Mốc tính theo", hg_kind_gio: "Giờ trong ngày", hg_kind_khoang: "Phút kể từ lúc bắt đầu",
  hg_run: "Cách chạy", hg_run_once: "Một lần", hg_run_repeat: "Lặp lại",
  hg_start: "Giờ bắt đầu chu kỳ",
  hg_steps: "Các bước", hg_steps_n: "{n} bước", hg_step_n: "Bước {n}",
  hg_minute: "Phút thứ", hg_capability: "Chức năng", hg_value: "Giá trị",
  hg_add_action: "Thêm hành động", hg_del_action: "Bớt hành động", hg_add_step: "Thêm bước",
  hg_invalid: "Cần tên, ít nhất một bước có hành động, và chọn ngày nếu lặp lại.",
  hg_no_cap: "Sản phẩm này chưa khai chức năng nào được phép đặt trong bước.",
  dev_rename: "Đổi tên thiết bị",
  dev_fav: "Ghim thiết bị",
  dev_shared: "được chia sẻ",
  dev_them_moi: "Thêm mới…",
  dev_chua_gan_nha: "Nhà: chưa gán",
  dev_chua_gan_phong: "Phòng: chưa gán",
  dev_chua_gan_nhom: "Nhóm: chưa gán",
  hg_loi_ten: "Chương trình cần có tên.",
  hg_loi_hd: "Bước {n} chưa có hành động nào.",
  hg_loi_cap: "Bước {n} dùng chức năng không còn được phép — chọn lại.",
  hg_loi_trung: "Bước {n} trùng giờ với một bước trước đó.",
  hg_loi_tang: "Bước {n} phải muộn hơn bước trước.",
  hg_loi_moc: "Bước {n}: phút phải nằm trong 1–1440.",
  hg_loi_ngay: "Lặp lại thì phải chọn ít nhất một ngày.",
  hg_loi_batdau: "Chu kỳ theo khoảng cần giờ bắt đầu.",
  pick_device: "Chọn thiết bị",
  supplies: "Vật tư",
  supplies_empty: "Chưa theo dõi vật tư nào.",
  supplies_add: "Thêm vật tư",
  supplies_add_hint: "Có serial chính hãng thì nhập serial để được xác thực; không có thì đặt tên tự do.",
  supplies_name: "Tên vật tư",
  supplies_serial: "Serial chính hãng (nếu có)",
  supplies_replace: "Thay",
  supplies_life: "Tuổi thọ {ngay} ngày",
  supplies_life_edit: "Sửa tuổi thọ",
  supplies_drop: "Bỏ",
  supplies_drop_confirm: "Bỏ theo dõi?",
  supplies_unverified: "chưa xác thực", next: "Sau",
  hide_device: "Ẩn thiết bị khỏi danh sách",
};
const en: Record<string, string> = {
  on: "On", off: "Off", "common.on": "On", "common.off": "Off",
  understood: "Got it", cancel: "Cancel", close: "Close", back: "Back",
  pin: "Pin", unpin: "Unpin", confirm_delete: "Delete?",
  loading: "Loading…", working: "Connecting…",
  nav_home: "Home", nav_devices: "Devices", nav_automation: "Automation", nav_services: "Services", nav_discover: "Discover",
  all_houses: "All homes", all_rooms: "All rooms",
  add_device: "Add device", pick_room: "Pick a room",
  no_device: "No devices yet",
  no_device_hint: "Add a device or change the filters.",
  unassigned_room: "No room assigned",
  offline: "Offline",
  auto_if: "If–Then", auto_time: "Schedule",
  auto_quota_full: "Rule limit reached ({n}). Delete one to add another.",
  auto_empty: "No automation yet.<br>If–Then: hotter than 30°C turns the fan on. Schedule: several stages, one action each.",
  if_label: "If", then_label: "Then",
  auto_run: "Run now", auto_delete: "Delete", notif_delete: "Delete this notification",
  auto_from_device: "From devices",
  auto_from_device_hint: "Device timer programs — edit them on the device screen.",
  shadow_tag: "shadow",
  svc_maintenance: "Maintenance", svc_warranty: "Official warranty",
  svc_activate: "Activate warranty", svc_shop: "Shop",
  dh_title: "Discover Livotec.com",
  dh_sub: "Browse the full catalogue, tech news and the latest offers on the official site",
  dh_btn: "Open website",
  menu_title: "Menu",
  menu_spaces: "Homes / Rooms / Groups",
  menu_members: "Members & sharing",
  menu_devices: "Devices",
  menu_add: "Add device / Wi-Fi setup",
  menu_virtual: "Virtual devices",
  logout: "Sign out",
  version_line: "Livotec Aiotec Smart · {ban}",
  menu_tai_khoan: "Account",
  menu_doi_mk: "Change password",
  menu_doi_ten: "Change name",
  dt_ten: "Display name",
  dt_ten_ph: "Enter a display name",
  dt_loi_trong: "Please enter a name",
  dt_loi_dai: "Name can be at most {n} characters",
  dt_chua_bat: "Could not change the name — this feature is waiting to be enabled.",
  anh_doi: "Change profile photo",
  anh_chon: "Choose photo",
  anh_loi_kieu: "Please choose an image file",
  anh_chua_bat: "Could not change the profile photo — this feature is waiting to be enabled.",
  menu_ngon_ngu: "Language",
  menu_giao_dien: "Appearance",
  gd_toi: "Dark",
  gd_sang: "Light",
  gd_he_thong: "System",
  menu_thong_bao: "Notifications",
  menu_thong_bao_mo_ta: "Unread badge on the bell",
  chu_co: "Text size",
  co_vua: "Default",
  co_lon: "Large",
  co_rat_lon: "Extra large",
  chu_xem_truoc: "The living room air conditioner is on at 26°C.",
  dmk_cu: "Current password",
  dmk_cu_ph: "Enter your current password",
  dmk_moi: "New password",
  dmk_moi_ph: "Enter a new password (≥ 8 characters)",
  dmk_nhap_lai: "Confirm new password",
  dmk_loi_cu: "Please enter your current password",
  dmk_loi_trung: "The new password must differ from the current one",
  dmk_chua_bat: "Could not change the password — this feature is waiting to be enabled.",
  dmk_xong: "Password changed.",
  notif_title: "Notifications", notif_empty: "No notifications", notif_clear: "Clear all",
  login_btn: "Sign in",
  dn_tai_khoan: "Account",
  dn_tai_khoan_ph: "Email or phone number",
  dn_pw: "Password",
  dn_pw_ph: "Enter your password (≥ 8 characters)",
  dn_hien: "Show password",
  dn_an: "Hide password",
  dn_ghi_nho: "Remember me",
  dn_quen: "Forgot password?",
  dn_chua_co: "Don't have an account?",
  dn_dk_ngay: "Sign up now",
  dn_quay_lai: "Back to sign in",
  dn_loi_id_trong: "Please enter your email or phone number",
  dn_loi_id_sai: "Invalid email or phone number",
  dn_loi_pw_trong: "Please enter your password",
  qm_title: "Forgot password",
  qm_lead: "Enter the email or phone number you signed up with. We will send a code to reset your password.",
  qm_gui: "Send code",
  qm_chua_bat: "Could not send the code — this feature is waiting to be enabled.",
  dn_hoac: "or",
  dn_google: "Continue with Google",
  dn_google_chua_bat: "Google sign-in is not available yet — this feature is waiting to be enabled.",
  qm_da_gui: "Code sent",
  qm_da_gui_lead: "We sent a 6-digit code to {dich}. It is valid for 10 minutes.",
  qm_nhap_ma: "Enter code",
  qm_khong_nhan: "Didn't get a code?",
  qm_gui_lai: "Resend",
  qm_da_nho: "Remembered your password?",
  dk_title: "Create account",
  dk_lead: "It takes less than a minute.",
  dk_ten: "Full name",
  dk_ten_ph: "Jane Doe",
  dk_pw2: "Confirm password",
  dk_btn: "Sign up",
  dk_da_co: "Already have an account?",
  dk_loi_ten: "Please enter your full name",
  dk_loi_pw_ngan: "Password must be at least {n} characters",
  dk_loi_pw2: "Passwords do not match",
  login_lang: "Language",
  login_bad: "Wrong account or password.",
  placeholder_msg: "This feature gets its own screen in the release build.", ac_room_temp: "Room Temperature",
  save: "Save",
  rule_conds: "{n} conditions", rule_gates: "{n} only when", rule_excl: "{n} except when", rule_actions: "{n} actions",
  rule_history: "Run history", rule_history_empty: "Never run yet.",
  rule_history_mock: "Run history lives on the server — not available in mock mode.",
  rule_stop: "Stop program",
  hg_title: "Device timers", hg_open: "Timers",
  hg_mock: "Timers live on the IoTX server. The app runs in mock mode, so this screen is unavailable.",
  hg_unsupported: "This product does not support timers.",
  hg_one_shot: "On / off timer", hg_none: "No timer set.",
  hg_will_on: "Will turn on", hg_will_off: "Will turn off", hg_cancel: "Cancel timer",
  hg_then_on: "Turn on", hg_then_off: "Turn off",
  hg_at_time: "At a time", hg_after: "After a delay", hg_at: "Time", hg_minutes: "Minutes ({min}–{max})",
  hg_set: "Set timer", hg_replace_note: "One timer per device — a new one replaces the old.",
  hg_programs: "Programs", hg_no_program: "No programs yet.",
  hg_new_program: "New program", hg_edit_program: "Edit program",
  hg_xoa_that: "Delete?", hg_khoa_sua: "Running mid-way — stop using it before editing.",
  hg_in_use: "in use", hg_use: "Use", hg_unuse: "Stop using",
  hg_running: "Program running, {n} steps done.",
  hg_revoked: "{n} capabilities revoked",
  hg_program_name: "Program name",
  hg_kind: "Steps measured by", hg_kind_gio: "Clock time", hg_kind_khoang: "Minutes from start",
  hg_run: "Run", hg_run_once: "Once", hg_run_repeat: "Repeat",
  hg_start: "Cycle start time",
  hg_steps: "Steps", hg_steps_n: "{n} steps", hg_step_n: "Step {n}",
  hg_minute: "Minute", hg_capability: "Capability", hg_value: "Value",
  hg_add_action: "Add action", hg_del_action: "Remove action", hg_add_step: "Add step",
  hg_invalid: "Needs a name, at least one step with an action, and days if repeating.",
  hg_no_cap: "This product declares no capability allowed inside a step.",
  dev_rename: "Rename device",
  dev_fav: "Pin device",
  dev_shared: "shared with you",
  dev_them_moi: "New…",
  dev_chua_gan_nha: "House: unassigned",
  dev_chua_gan_phong: "Room: unassigned",
  dev_chua_gan_nhom: "Group: unassigned",
  hg_loi_ten: "The program needs a name.",
  hg_loi_hd: "Step {n} has no action yet.",
  hg_loi_cap: "Step {n} uses a capability that is no longer allowed — pick another.",
  hg_loi_trung: "Step {n} repeats a time an earlier step already uses.",
  hg_loi_tang: "Step {n} must come later than the step before it.",
  hg_loi_moc: "Step {n}: the minute must be between 1 and 1440.",
  hg_loi_ngay: "Repeating programs need at least one day.",
  hg_loi_batdau: "An interval cycle needs a start time.",
  pick_device: "Pick a device",
  supplies: "Consumables",
  supplies_empty: "Nothing tracked yet.",
  supplies_add: "Add consumable",
  supplies_add_hint: "Enter an official serial to get it verified, or just give it a name.",
  supplies_name: "Name",
  supplies_serial: "Official serial (optional)",
  supplies_replace: "Replace",
  supplies_life: "Life {ngay} days",
  supplies_life_edit: "Edit life",
  supplies_drop: "Drop",
  supplies_drop_confirm: "Stop tracking?",
  supplies_unverified: "unverified", next: "Next",
  hide_device: "Hide this device from the list",
};
const fil: Record<string, string> = {
  on: "On", off: "Off", "common.on": "On", "common.off": "Off",
  understood: "Naiintindihan", cancel: "Kanselahin", close: "Isara", back: "Bumalik",
  pin: "I-pin", unpin: "Alisin ang pin", confirm_delete: "Burahin?",
  loading: "Naglo-load…", working: "Kumokonekta…",
  nav_home: "Tahanan", nav_devices: "Device", nav_automation: "Automation", nav_services: "Serbisyo", nav_discover: "Tuklasin",
  all_houses: "Lahat ng tahanan", all_rooms: "Lahat ng silid",
  add_device: "Magdagdag ng device", pick_room: "Pumili ng silid",
  no_device: "Wala pang device",
  no_device_hint: "Magdagdag ng device o baguhin ang filter.",
  unassigned_room: "Wala pang silid",
  offline: "Offline",
  auto_if: "Kung–Kaya", auto_time: "Ayon sa oras",
  auto_quota_full: "Umabot na sa {n} na patakaran. Magbura ng isa para makadagdag.",
  auto_empty: "Wala pang automation.<br>Kung–Kaya: kapag lumampas sa 30°C, buksan ang fan. Ayon sa oras: hatiin sa mga yugto.",
  if_label: "Kung", then_label: "Kaya",
  auto_run: "Patakbuhin", auto_delete: "Tanggalin", notif_delete: "Burahin ang abisong ito",
  auto_from_device: "Mula sa device",
  auto_from_device_hint: "Timer program ng device — i-edit sa screen ng device.",
  shadow_tag: "pagsubok",
  svc_maintenance: "Maintenance", svc_warranty: "Opisyal na warranty",
  svc_activate: "I-activate ang warranty", svc_shop: "Mamili",
  dh_title: "Tuklasin ang Livotec.com",
  dh_sub: "Tingnan ang lahat ng produkto, balita at pinakabagong alok sa opisyal na website",
  dh_btn: "Buksan ang website",
  menu_title: "Menu",
  menu_spaces: "Tahanan / Silid / Grupo",
  menu_members: "Miyembro at pagbabahagi",
  menu_devices: "Device",
  menu_add: "Magdagdag ng device / Wi-Fi setup",
  menu_virtual: "Virtual na device",
  logout: "Mag-sign out",
  version_line: "Livotec Aiotec Smart · {ban}",
  menu_tai_khoan: "Account",
  menu_doi_mk: "Palitan ang password",
  menu_doi_ten: "Palitan ang pangalan",
  dt_ten: "Pangalang ipapakita",
  dt_ten_ph: "Ilagay ang pangalang ipapakita",
  dt_loi_trong: "Ilagay ang pangalan",
  dt_loi_dai: "Hanggang {n} character lang ang pangalan",
  dt_chua_bat: "Hindi mapalitan ang pangalan — hinihintay pang i-enable ang tampok na ito.",
  anh_doi: "Palitan ang larawan sa profile",
  anh_chon: "Pumili ng larawan",
  anh_loi_kieu: "Pumili ng file ng larawan",
  anh_chua_bat: "Hindi mapalitan ang larawan sa profile — hinihintay pang i-enable ang tampok na ito.",
  menu_ngon_ngu: "Wika",
  menu_giao_dien: "Hitsura",
  gd_toi: "Madilim",
  gd_sang: "Maliwanag",
  gd_he_thong: "Sistema",
  menu_thong_bao: "Mga abiso",
  menu_thong_bao_mo_ta: "Badge ng hindi pa nababasa sa kampana",
  chu_co: "Laki ng teksto",
  co_vua: "Default",
  co_lon: "Malaki",
  co_rat_lon: "Napakalaki",
  chu_xem_truoc: "Nakabukas ang aircon sa sala sa 26°C.",
  dmk_cu: "Kasalukuyang password",
  dmk_cu_ph: "Ilagay ang kasalukuyang password",
  dmk_moi: "Bagong password",
  dmk_moi_ph: "Ilagay ang bagong password (≥ 8 character)",
  dmk_nhap_lai: "Ulitin ang bagong password",
  dmk_loi_cu: "Ilagay ang iyong kasalukuyang password",
  dmk_loi_trung: "Dapat iba ang bagong password sa kasalukuyan",
  dmk_chua_bat: "Hindi mapalitan ang password — hinihintay pang i-enable ang tampok na ito.",
  dmk_xong: "Napalitan na ang password.",
  notif_title: "Mga abiso", notif_empty: "Walang abiso", notif_clear: "Burahin lahat",
  login_btn: "Mag-sign in",
  dn_tai_khoan: "Account",
  dn_tai_khoan_ph: "Email o numero ng telepono",
  dn_pw: "Password",
  dn_pw_ph: "Ilagay ang password (≥ 8 character)",
  dn_hien: "Ipakita ang password",
  dn_an: "Itago ang password",
  dn_ghi_nho: "Tandaan ako",
  dn_quen: "Nakalimutan ang password?",
  dn_chua_co: "Wala ka pang account?",
  dn_dk_ngay: "Mag-sign up ngayon",
  dn_quay_lai: "Bumalik sa sign in",
  dn_loi_id_trong: "Ilagay ang iyong email o numero ng telepono",
  dn_loi_id_sai: "Hindi wastong email o numero ng telepono",
  dn_loi_pw_trong: "Ilagay ang iyong password",
  qm_title: "Nakalimutan ang password",
  qm_lead: "Ilagay ang email o numerong ginamit mo sa pag-sign up. Magpapadala kami ng code para i-reset ang password.",
  qm_gui: "Ipadala ang code",
  qm_chua_bat: "Hindi maipadala ang code — hinihintay pang i-enable ang tampok na ito.",
  dn_hoac: "o",
  dn_google: "Magpatuloy gamit ang Google",
  dn_google_chua_bat: "Hindi pa makapag-sign in gamit ang Google — hinihintay pang i-enable ang tampok na ito.",
  qm_da_gui: "Naipadala ang code",
  qm_da_gui_lead: "Nagpadala kami ng 6-digit na code sa {dich}. May bisa ito nang 10 minuto.",
  qm_nhap_ma: "Ilagay ang code",
  qm_khong_nhan: "Hindi natanggap ang code?",
  qm_gui_lai: "Ipadala muli",
  qm_da_nho: "Naalala na ang password?",
  dk_title: "Gumawa ng account",
  dk_lead: "Wala pang isang minuto.",
  dk_ten: "Buong pangalan",
  dk_ten_ph: "Juan dela Cruz",
  dk_pw2: "Ulitin ang password",
  dk_btn: "Mag-sign up",
  dk_da_co: "May account ka na?",
  dk_loi_ten: "Ilagay ang iyong buong pangalan",
  dk_loi_pw_ngan: "Dapat hindi bababa sa {n} character ang password",
  dk_loi_pw2: "Hindi magkatugma ang mga password",
  login_lang: "Wika",
  login_bad: "Mali ang account o password.",
  placeholder_msg: "May sariling screen ang feature na ito sa release build.", ac_room_temp: "Temperatura ng Silid",
  save: "I-save",
  rule_conds: "{n} kondisyon", rule_gates: "{n} kung", rule_excl: "{n} maliban", rule_actions: "{n} aksyon",
  rule_history: "Kasaysayan ng pagtakbo", rule_history_empty: "Hindi pa tumatakbo.",
  rule_history_mock: "Nasa server ang kasaysayan — wala sa mock mode.",
  rule_stop: "Itigil ang programa",
  hg_title: "Timer ng device", hg_open: "Timer",
  hg_mock: "Nasa IoTX server ang timer. Mock mode ang app kaya hindi pa magagamit ito.",
  hg_unsupported: "Hindi sinusuportahan ng produktong ito ang timer.",
  hg_one_shot: "On / off timer", hg_none: "Walang nakatakdang timer.",
  hg_will_on: "Bubuksan", hg_will_off: "Isasara", hg_cancel: "Kanselahin",
  hg_then_on: "Buksan", hg_then_off: "Isara",
  hg_at_time: "Sa oras", hg_after: "Pagkalipas ng", hg_at: "Oras", hg_minutes: "Minuto ({min}–{max})",
  hg_set: "Itakda", hg_replace_note: "Isang timer bawat device — papalitan ang luma.",
  hg_programs: "Mga programa", hg_no_program: "Wala pang programa.",
  hg_new_program: "Bagong programa", hg_edit_program: "I-edit ang programa",
  hg_xoa_that: "Burahin?", hg_khoa_sua: "Tumatakbo pa — itigil muna ang paggamit bago i-edit.",
  hg_in_use: "ginagamit", hg_use: "Gamitin", hg_unuse: "Itigil",
  hg_running: "Tumatakbo, {n} hakbang na ang tapos.",
  hg_revoked: "{n} kakayahan ang binawi",
  hg_program_name: "Pangalan ng programa",
  hg_kind: "Batayan ng hakbang", hg_kind_gio: "Oras sa araw", hg_kind_khoang: "Minuto mula sa simula",
  hg_run: "Pagtakbo", hg_run_once: "Isang beses", hg_run_repeat: "Ulitin",
  hg_start: "Oras ng simula",
  hg_steps: "Mga hakbang", hg_steps_n: "{n} hakbang", hg_step_n: "Hakbang {n}",
  hg_minute: "Minuto", hg_capability: "Kakayahan", hg_value: "Halaga",
  hg_add_action: "Magdagdag ng aksyon", hg_del_action: "Bawasan", hg_add_step: "Magdagdag ng hakbang",
  hg_invalid: "Kailangan ng pangalan, kahit isang hakbang na may aksyon, at araw kung uulitin.",
  hg_no_cap: "Walang kakayahang pinapayagan sa hakbang ang produktong ito.",
  dev_rename: "Palitan ang pangalan",
  dev_fav: "I-pin ang device",
  dev_shared: "ibinahagi sa iyo",
  dev_them_moi: "Bago…",
  dev_chua_gan_nha: "Bahay: wala pa",
  dev_chua_gan_phong: "Kwarto: wala pa",
  dev_chua_gan_nhom: "Grupo: wala pa",
  hg_loi_ten: "Kailangan ng pangalan ang programa.",
  hg_loi_hd: "Wala pang aksyon ang hakbang {n}.",
  hg_loi_cap: "Gumagamit ang hakbang {n} ng kakayahang hindi na pinapayagan — pumili ng iba.",
  hg_loi_trung: "Kapareho ng oras ng naunang hakbang ang hakbang {n}.",
  hg_loi_tang: "Dapat mas huli ang hakbang {n} kaysa sa naunang hakbang.",
  hg_loi_moc: "Hakbang {n}: dapat nasa 1–1440 ang minuto.",
  hg_loi_ngay: "Kailangan ng kahit isang araw kapag paulit-ulit.",
  hg_loi_batdau: "Kailangan ng oras ng simula ang siklong panagitan.",
  pick_device: "Pumili ng device",
  supplies: "Consumables",
  supplies_empty: "Wala pang sinusubaybayan.",
  supplies_add: "Magdagdag",
  supplies_add_hint: "Maglagay ng opisyal na serial para ma-verify, o pangalan na lang.",
  supplies_name: "Pangalan",
  supplies_serial: "Opisyal na serial (opsyonal)",
  supplies_replace: "Palitan",
  supplies_life: "Buhay {ngay} araw",
  supplies_life_edit: "Baguhin ang buhay",
  supplies_drop: "Alisin",
  supplies_drop_confirm: "Itigil ang pagsubaybay?",
  supplies_unverified: "hindi verified", next: "Susunod",
  hide_device: "Itago ang device sa listahan",
};
/* ------------------------------------------------------------------ */
/* Chữ của tám màn thiết bị mới (bản giao diện MasterDetail)            */
/* ------------------------------------------------------------------ */
const MOI: Record<MaNgonNgu, Record<string, string>> = {
  vi: {
    online: "Đang kết nối",
    close: "Đóng",
    khung_more: "Xem thêm",
    khung_less: "Thu gọn",
    khong_co_khuon: "Sản phẩm này chưa khai capability nào, nên chưa có gì để điều khiển.",
    hg_chua_dat: "chưa đặt gì — chạm để cài",
    hg_ghim_bat: "sẽ BẬT lúc {luc}",
    hg_ghim_tat: "sẽ TẮT lúc {luc}",
    hg_ghim_chay: "đang chạy “{ten}” — xong {n} bước",
    hg_ghim_dung: "đang dùng “{ten}”",
    nhac_offline: "Thiết bị đang ngoại tuyến — lệnh vẫn gửi được nhưng có thể chưa tới ngay.",
    chan_khongQuyen: "Bạn chỉ được xem thiết bị này. Nhờ chủ nhà cấp quyền điều khiển trong mục Thành viên.",
    chan_khong_lenh: "Catalog chưa khai lệnh cho “{ten}”, nên mục này chỉ để xem.",
    device: "Thiết bị",
    // bộ lọc nhà / nhóm
    pick_house: "Chọn nhà", pick_group: "Chọn nhóm", all_groups: "Tất cả nhóm",
    nhom_lam_mat: "Làm mát", nhom_bep: "Nhà bếp", nhom_nuoc: "Nước", nhom_khac: "Khác",
    // bếp từ
    // hút mùi
    // lọc nước
    // bình nóng lạnh
    // nồi cơm
    // quạt
  },
  en: {
    online: "Online",
    close: "Close",
    khung_more: "Show more",
    khung_less: "Show less",
    khong_co_khuon: "This product declares no capabilities, so there is nothing to control yet.",
    hg_chua_dat: "nothing set yet — tap to configure",
    hg_ghim_bat: "will turn ON at {luc}",
    hg_ghim_tat: "will turn OFF at {luc}",
    hg_ghim_chay: "running “{ten}” — {n} steps done",
    hg_ghim_dung: "using “{ten}”",
    nhac_offline: "The device is offline — commands still go out, but may not arrive right away.",
    chan_khongQuyen: "You only have view access. Ask the home owner for control rights under Members.",
    chan_khong_lenh: "The catalogue declares no command for “{ten}”, so it is view-only.",
    device: "Device",
    pick_house: "Pick a home", pick_group: "Pick a group", all_groups: "All groups",
    nhom_lam_mat: "Cooling", nhom_bep: "Kitchen", nhom_nuoc: "Water", nhom_khac: "Other",
  },
  fil: {
    online: "Online",
    close: "Isara",
    khung_more: "Magpakita pa",
    khung_less: "Bawasan",
    khong_co_khuon: "Walang naideklarang capability ang produktong ito, kaya wala pang makokontrol.",
    hg_chua_dat: "wala pang naka-set — pindutin para i-configure",
    hg_ghim_bat: "bubukas sa {luc}",
    hg_ghim_tat: "magsasara sa {luc}",
    hg_ghim_chay: "tumatakbo ang “{ten}” — {n} hakbang na tapos",
    hg_ghim_dung: "ginagamit ang “{ten}”",
    nhac_offline: "Offline ang device — naipapadala pa rin ang utos, pero baka hindi agad dumating.",
    chan_khongQuyen: "Tingin lang ang access mo. Humingi ng control rights sa may-ari sa ilalim ng Members.",
    chan_khong_lenh: "Walang naidedeklarang utos ang catalogue para sa “{ten}”, kaya tingin lang ito.",
    device: "Device",
    pick_house: "Pumili ng bahay", pick_group: "Pumili ng grupo", all_groups: "Lahat ng grupo",
    nhom_lam_mat: "Palamig", nhom_bep: "Kusina", nhom_nuoc: "Tubig", nhom_khac: "Iba pa",
  },
};
/* ------------------------------------------------------------------ */
/* Chữ của các panel quản lý: tự động, thiết bị ảo, thành viên, không   */
/* gian, thêm thiết bị. Trước đây nằm rải rác làm tham số mặc định cho  */
/* `t()` của hệ i18n thứ hai; gom về đây để app chỉ còn MỘT bảng chữ.   */
/* Chỉ điền tiếng Việt: `useChu` rơi bậc en/fil về vi, đúng y như hành  */
/* vi cũ (tham số mặc định trước đây cũng là tiếng Việt).               */
/* ------------------------------------------------------------------ */
const PANEL: Record<MaNgonNgu, Record<string, string>> = {
  vi: {
    "routine.previewFailed": "không xem trước được",
    "routine.and": "VÀ",
    "routine.or": "HOẶC",
    "common.delete": "Xoá",
    "routine.timeWindow": "Khung giờ",
    "common.to": "đến",
    "routine.noDays": "Không chọn ngày nào = mọi ngày",
    "routine.pickDevice": "Chọn thiết bị",
    "routine.pickCap": "Chọn chỉ số",
    "common.add": "Thêm",
    "common.back": "Quay lại",
    "routine.condTitle": "Tự động Nếu–Thì",
    "routine.title": "Tự động",
    "routine.namePhCond": "Tên, vd. Nóng thì bật quạt",
    "routine.if": "NẾU",
    "routine.allConds": "Phải đúng tất cả thì mới chạy.",
    "routine.onlyOpt": "CHỈ KHI (không bắt buộc)",
    "routine.onlyHint": "Rào cho phép — phải đúng hết thì mới chạy.",
    "routine.exceptOpt": "TRỪ KHI (không bắt buộc)",
    "routine.exceptHint": "Rào chặn — đúng một cái là không chạy.",
    "routine.thenMax": "THÌ (tối đa 20)",
    "routine.doWhat": "Làm gì",
    "routine.actionN": "hành động {n}",
    "routine.notifyDefault": "Tự động hoá vừa chạy",
    "common.device": "thiết bị",
    "routine.sendNotify": "Gửi thông báo",
    "routine.notifyText": "Nội dung thông báo",
    "routine.waitSeconds": "chờ (giây)",
    "routine.validityFull": "HIỆU LỰC (để trống = ngay và mãi mãi)",
    "routine.expiryHint": "Hết hạn thì tự động hoá tự tắt, không bị xoá.",
    "routine.hold": "Điều kiện phải đúng liên tục",
    "routine.holdNow": "ngay lập tức",
    "dur.30s": "30 giây",
    "dur.1m": "1 phút",
    "dur.5m": "5 phút",
    "routine.yield": "Nhường tay người dùng",
    "routine.noYield": "không nhường",
    "dur.15m": "15 phút",
    "dur.1h": "1 giờ",
    "routine.yieldHint": "Bạn vừa tự chỉnh thiết bị thì tự động hoá không đụng vào nó trong khoảng này.",
    "routine.preview": "Xem trước — bây giờ có chạy không?",
    "routine.willRun": "Ngay bây giờ sẽ chạy",
    "routine.wontRun": "Chưa chạy — {why}",
    "routine.pass": "đúng",
    "routine.fail": "sai",
    "routine.currently": "hiện {v}",
    "routine.shadowHint": "Tự động hoá mới luôn bắt đầu ở chế độ chạy thử: hệ ghi lại “lẽ ra đã chạy” nhưng chưa gửi lệnh thật.",
    "common.saving": "Đang lưu…",
    "common.save": "Lưu",
    "routine.value": "giá trị",
    "common.on": "Bật",
    "common.off": "Tắt",
    "virtual.external": "Nguồn ngoài",
    "virtual.externalDesc": "Thời tiết, chất lượng không khí",
    "virtual.phExternal": "Tên, vd. Thời tiết Hà Nội",
    "virtual.state": "Trạng thái nhà",
    "virtual.stateDesc": "Có người ở nhà, chế độ ngủ, đi vắng",
    "virtual.phState": "Tên, vd. Có người ở nhà",
    "virtual.button": "Nút bấm",
    "virtual.buttonDesc": "Về nhà, đi ngủ — bấm một cái là tự động hoá chạy",
    "virtual.phButton": "Tên, vd. Đi ngủ",
    "state.on": "Đang bật",
    "state.offNow": "Đang tắt",
    "virtual.pressCount": "đã bấm {n} lần",
    "virtual.humidity": "ẩm {v}%",
    "virtual.aqi": "không khí {v}",
    "virtual.noData": "chưa có dữ liệu — chờ lần lấy đầu tiên",
    "virtual.title": "Thiết bị ảo",
    "virtual.hint": "Thứ có tên và có trạng thái nhưng không phải máy móc trong nhà.",
    "common.create": "Tạo",
    "place.title": "Nơi",
    "virtual.pickPlace": "Chọn nơi",
    "virtual.limit": "Tối đa 10 thiết bị ảo. Cái nào đang được tự động hoá dùng thì không xoá được.",
    "common.close": "Đóng",
    "virtual.empty": "Chưa có thiết bị ảo nào.",
    "virtual.press": "Bấm",
    "share.viewOnly": "chỉ xem",
    "share.controlOnly": "chỉ điều khiển",
    "share.noDelete": "không được xóa",
    "share.fullAccess": "toàn quyền",
    "share.oneDevice": "một thiết bị",
    "share.needEmailHouse": "Nhập email và chọn nhà",
    "share.invited": "Đã mời — người này chưa có tài khoản, sẽ nhận khi đăng ký",
    "share.shared": "Đã chia sẻ ✓",
    "share.inviteFailed": "Không mời được — kiểm tra lại email",
    "share.permsUpdated": "Đã cập nhật quyền",
    "share.revoked": "Đã gỡ",
    "share.title": "Thành viên & chia sẻ",
    "share.invite": "Mời thành viên",
    "share.noHouse": "Bạn chưa có nhà nào để chia sẻ. Chỉ chủ nhà mới mời được thành viên — tạo nhà trong mục Quản lý Nhà / Phòng / Nhóm trước đã.",
    "share.emailPh": "Email người nhận",
    "share.scopeHouse": "Cả nhà",
    "share.scopeRoom": "Một phòng",
    "share.scopeDevice": "Một thiết bị",
    "share.pickHouse": "Chọn nhà",
    "share.pickRoom": "Chọn phòng",
    "share.defaultHint": "Mặc định thành viên dùng được mọi thứ như bạn. Siết bớt trong “Cài đặt nâng cao”.",
    "share.advanced": "Cài đặt nâng cao",
    "share.blockDelete": "Không cho xóa (vẫn tạo mới được)",
    "common.working": "Đang kết nối…",
    "share.doShare": "Chia sẻ",
    "share.sharedWith": "Đã chia sẻ cho",
    "share.noneShared": "Chưa chia sẻ cho ai.",
    "share.pending": "chờ đăng ký",
    "share.revokeConfirm": "Gỡ quyền truy cập của thành viên này?",
    "share.revoke": "Gỡ quyền",
    "share.sharedToMe": "Người khác chia sẻ cho tôi",
    "share.noneToMe": "Chưa có ai chia sẻ cho bạn.",
    "routine.condN": "điều kiện {n}",
    "share.oneRoom": "phòng {name}",
    "share.wholeHouse": "cả nhà {name}",
    "op.eq": "bằng",
    "op.neq": "khác",
    "op.gt": "lớn hơn",
    "op.lt": "nhỏ hơn",
    "dow.sun": "CN",
    "dow.mon": "T2",
    "dow.tue": "T3",
    "dow.wed": "T4",
    "dow.thu": "T5",
    "dow.fri": "T6",
    "dow.sat": "T7",
    notif_empty: "Chưa có thông báo nào.",
    notif_clear: "Xoá tất cả thông báo",
    notif_delete: "Xoá thông báo này",
    club_kitchen: "Hội Yêu Bếp",
    club_aircon: "Hội Điều Hòa",
    club_water: "Hội Máy Lọc Nước",
    club_fan: "Hội Quạt",
    promo_aircon: "Khuyến mãi điều hòa I-Boost",
    promo_wh: "Khuyến mãi bình nóng lạnh",
    loc_nha: "Nhà",
    loc_phong: "Phòng",
    loc_nhom: "Nhóm",
    "routine.op": "toán tử",
    "routine.actionKind": "kiểu hành động",
    "routine.startsAt": "bắt đầu",
    "routine.endsAt": "kết thúc",
    "virtual.mockNote": "Màn này cần nối máy chủ IoTX. Ứng dụng đang chạy ở chế độ mock nên chưa tạo được thiết bị ảo.",
    splash_loading: "Đang khởi động Livotec Home…",
    toast_close: "Đóng thông báo",
    supplies_new: "Vật tư mới",
    banner_aircon: "Công nghệ i-Boost — Điều hòa I30J",
    banner_cooktop: "Bếp Điện Từ Đôi LIO-888VT",
    banner_water_title: "Máy Lọc Nước 886i",
    banner_water_sub: "Công nghệ I-Vision thông minh",
    "spaces.title": "Quản lý không gian",
    "spaces.newPh": "Tên {loai} mới",
    "spaces.syncNote": "Không gian được đồng bộ với tài khoản Livotec của bạn.",
    "add.title": "Thêm thiết bị",
    "add.how": "Bạn muốn thêm thiết bị bằng cách nào?",
    "add.qr": "Quét mã QR",
    "add.qrHint": "Nhanh nhất · mã ở trên thân thiết bị",
    "add.serial": "Nhập mã thiết bị",
    "add.serialHint": "Mạch đã có sẵn Wi-Fi và chứng thư — chỉ cần serial in trên vỏ",
    "add.scanQr": "Đặt mã QR vào khung",
    "add.enterSerial": "Nhập serial thiết bị",
    "add.code": "Mã thiết bị",
    "add.identify": "Nhận diện thiết bị",
    "add.found": "Đã tìm thấy quạt Livotec",
    "add.waitingWifi": "Thiết bị đang chờ cấu hình Wi-Fi",
    "add.wifi": "Mạng Wi-Fi 2.4 GHz",
    "add.wifiPass": "Mật khẩu Wi-Fi",
    "add.wifiPassPh": "Chỉ dùng tại máy bạn — bước này đang mô phỏng",
    "add.connect": "Kết nối",
    "add.pairing": "Đang ghép nối với {wifi}",
    "add.pairingHint": "Đảm bảo đèn Wi-Fi trên quạt đang nhấp nháy.",
    "add.simulate": "Mô phỏng kết nối thành công",
    "add.online": "Thiết bị đã trực tuyến",
    "add.name": "Tên thiết bị",
    "add.room": "Phòng",
    "add.finish": "Hoàn tất",
    "add.done": "Đã thêm thiết bị",
    "add.ready": "{name} đã sẵn sàng điều khiển.",
    "add.home": "Về trang chủ",
    "add.defaultName": "Quạt mới",
    "add.defaultHouse": "Nhà của tôi",
    "add.defaultRoom": "Phòng khách",
    "add.defaultGroup": "Mặc định",
    "add.tenTem": "Tên trên tem",
    "add.tenTemPh": "vd. fan81029",
    "add.maSo": "Mã claim 5 số",
    "add.maSoPh": "Mã 5 số trên tem",
    "add.moPhong": "Bản web mô phỏng bước này — ghép nối Bluetooth thật cần app di động.",
    "add.machPhaiOnline": "Mạch phải đang cắm điện và online.",
    "add.chuaOnline": "Đã nhận mạch nhưng chưa thấy nó online — kiểm tra nguồn và Wi-Fi.",
    "add.moCamera": "Mở camera để quét",
    "add.dungQuet": "Dừng quét",
    "add.quetKhongDuoc": "Không mở được camera — kiểm tra quyền camera (và trang phải chạy HTTPS), hoặc gõ tay bên dưới.",
    "add.quetCanHttps": "Trang đang mở qua http:// nên trình duyệt không cho dùng camera — mở bằng https:// hoặc localhost, hoặc gõ tay bên dưới.",
    "add.daQuet": "Đã đọc mã trên tem.",
    "add.maWifi": "Đây là mã ① (Wi-Fi của mạch). Hãy quét mã ② “Thêm vào Livotec”.",
    "add.quetThieuTen": "Mã không ghi tên trên tem — gõ tay vào ô bên dưới.",
    "add.timBle": "Tìm thiết bị qua Bluetooth",
    "add.daGhepNoi": "Đã ghép nối với {ten}",
    "add.bleChon": "Trình duyệt sẽ hiện hộp chọn — chọn thiết bị tên “{ten}” (hoặc PROV_…).",
    "add.bleKhongHoTro": "Trình duyệt này không có Web Bluetooth (iPhone/iPad, Firefox) — bước ghép nối được mô phỏng; ghép thật cần app di động.",
    "add.bleCanHttps": "Trang đang mở qua http:// nên trình duyệt tắt Web Bluetooth — mở bằng https:// hoặc localhost để ghép nối thật; ở đây bước này được mô phỏng.",
    "add.bleHuy": "Chưa chọn thiết bị nào.",
    "add.bleLoi": "Không ghép nối được: {loi}",
    "add.boQuaBle": "Bỏ qua (mô phỏng)",
    "add.wifiMoPhongSauBle": "Đã ghép nối thật; gửi cấu hình Wi-Fi xuống mạch còn mô phỏng — chờ đặc tả Security 2 của firmware.",
    "add.tiepTuc": "Tiếp tục",
  },
  en: {
    "routine.previewFailed": "preview failed",
    "routine.and": "AND",
    "routine.or": "OR",
    "common.delete": "Delete",
    "routine.timeWindow": "Time window",
    "common.to": "to",
    "routine.noDays": "No days selected = every day",
    "routine.pickDevice": "Pick a device",
    "routine.pickCap": "Pick a reading",
    "common.add": "Add",
    "common.back": "Back",
    "routine.condTitle": "If–Then automation",
    "routine.title": "Automation",
    "routine.namePhCond": "Name, e.g. Hot → turn fan on",
    "routine.if": "IF",
    "routine.allConds": "All must be true for it to run.",
    "routine.onlyOpt": "ONLY WHEN (optional)",
    "routine.onlyHint": "Allow gate — all must be true to run.",
    "routine.exceptOpt": "EXCEPT WHEN (optional)",
    "routine.exceptHint": "Block gate — any one true stops it.",
    "routine.thenMax": "THEN (max 20)",
    "routine.doWhat": "What to do",
    "routine.actionN": "action {n}",
    "routine.notifyDefault": "Automation just ran",
    "common.device": "device",
    "routine.sendNotify": "Send a notification",
    "routine.notifyText": "Notification text",
    "routine.waitSeconds": "wait (seconds)",
    "routine.validityFull": "VALIDITY (blank = now and forever)",
    "routine.expiryHint": "When it expires the automation turns itself off; it is not deleted.",
    "routine.hold": "Condition must stay true for",
    "routine.holdNow": "immediately",
    "dur.30s": "30 seconds",
    "dur.1m": "1 minute",
    "dur.5m": "5 minutes",
    "routine.yield": "Yield to the user",
    "routine.noYield": "never yield",
    "dur.15m": "15 minutes",
    "dur.1h": "1 hour",
    "routine.yieldHint": "If you just adjusted a device yourself, the automation leaves it alone for this long.",
    "routine.preview": "Preview — would it run right now?",
    "routine.willRun": "Would run right now",
    "routine.wontRun": "Would not run — {why}",
    "routine.pass": "true",
    "routine.fail": "false",
    "routine.currently": "currently {v}",
    "routine.shadowHint": "New automations start in shadow mode: the system logs “would have run” but sends no real command yet.",
    "common.saving": "Saving…",
    "common.save": "Save",
    "routine.value": "value",
    "routine.op": "operator",
    "routine.actionKind": "action kind",
    "routine.startsAt": "starts at",
    "routine.endsAt": "ends at",
    "common.on": "On",
    "common.off": "Off",
    "virtual.external": "External source",
    "virtual.externalDesc": "Weather, air quality",
    "virtual.phExternal": "Name, e.g. Hanoi weather",
    "virtual.state": "Home state",
    "virtual.stateDesc": "Someone home, sleep mode, away",
    "virtual.phState": "Name, e.g. Someone home",
    "virtual.button": "Button",
    "virtual.buttonDesc": "Coming home, going to bed — one tap runs the automation",
    "virtual.phButton": "Name, e.g. Bedtime",
    "state.on": "On",
    "state.offNow": "Off",
    "virtual.pressCount": "pressed {n} times",
    "virtual.humidity": "humidity {v}%",
    "virtual.aqi": "air {v}",
    "virtual.noData": "no data yet — waiting for the first fetch",
    "virtual.title": "Virtual devices",
    "virtual.hint": "Things with a name and a state that aren't appliances in your home.",
    "virtual.mockNote": "This screen needs the IoTX server. The app is running in mock mode, so virtual devices can't be created yet.",
    "common.create": "Create",
    "place.title": "Place",
    "virtual.pickPlace": "Pick a place",
    "virtual.limit": "Up to 10 virtual devices. One used by an automation cannot be deleted.",
    "common.close": "Close",
    "virtual.empty": "No virtual devices yet.",
    "virtual.press": "Press",
    "share.viewOnly": "view only",
    "share.controlOnly": "control only",
    "share.noDelete": "cannot delete",
    "share.fullAccess": "full access",
    "share.oneDevice": "one device",
    "share.needEmailHouse": "Enter an email and pick a house",
    "share.invited": "Invited — this person has no account yet and will get access on sign-up",
    "share.shared": "Shared ✓",
    "share.inviteFailed": "Could not invite — check the email",
    "share.permsUpdated": "Permissions updated",
    "share.revoked": "Removed",
    "share.title": "Members & sharing",
    "share.invite": "Invite a member",
    "share.noHouse": "You have no house to share. Only a house owner can invite members — create a house under Manage houses / rooms / groups first.",
    "share.emailPh": "Recipient email",
    "share.scopeHouse": "Whole house",
    "share.scopeRoom": "One room",
    "share.scopeDevice": "One device",
    "share.pickHouse": "Pick a house",
    "share.pickRoom": "Pick a room",
    "share.defaultHint": "By default a member can do everything you can. Restrict under “Advanced”.",
    "share.advanced": "Advanced",
    "share.blockDelete": "No deleting (can still create)",
    "common.working": "Connecting…",
    "share.doShare": "Share",
    "share.sharedWith": "Shared with",
    "share.noneShared": "Not shared with anyone yet.",
    "share.pending": "pending sign-up",
    "share.revokeConfirm": "Remove this member's access?",
    "share.revoke": "Remove access",
    "share.sharedToMe": "Shared with me",
    "share.noneToMe": "Nobody has shared with you yet.",
    "routine.condN": "condition {n}",
    "share.oneRoom": "room {name}",
    "share.wholeHouse": "whole house {name}",
    "op.eq": "equals",
    "op.neq": "not equal",
    "op.gt": "greater than",
    "op.lt": "less than",
    "dow.sun": "Su",
    "dow.mon": "Mo",
    "dow.tue": "Tu",
    "dow.wed": "We",
    "dow.thu": "Th",
    "dow.fri": "Fr",
    "dow.sat": "Sa",
    notif_empty: "No notifications yet.",
    notif_clear: "Clear all notifications",
    notif_delete: "Delete this notification",
    club_kitchen: "Kitchen Lovers Club",
    club_aircon: "Air Conditioner Club",
    club_water: "Water Purifier Club",
    club_fan: "Fan Club",
    promo_aircon: "I-Boost air conditioner promotion",
    promo_wh: "Water heater promotion",
    loc_nha: "House",
    loc_phong: "Room",
    loc_nhom: "Group",
    splash_loading: "Starting Livotec Home…",
    toast_close: "Dismiss",
    supplies_new: "New supply",
    banner_aircon: "i-Boost technology — I30J air conditioner",
    banner_cooktop: "LIO-888VT double induction cooktop",
    banner_water_title: "886i Water Purifier",
    banner_water_sub: "Smart I-Vision technology",
    "spaces.title": "Manage spaces",
    "spaces.newPh": "New {loai} name",
    "spaces.syncNote": "Spaces sync with your Livotec account.",
    "add.title": "Add a device",
    "add.how": "How would you like to add the device?",
    "add.qr": "Scan QR code",
    "add.qrHint": "Fastest · the code is on the device body",
    "add.serial": "Enter device code",
    "add.serialHint": "Wi-Fi and certificate are already loaded — you only need the serial on the case",
    "add.scanQr": "Place the QR code in the frame",
    "add.enterSerial": "Enter the device serial",
    "add.code": "Device code",
    "add.identify": "Identify device",
    "add.found": "Livotec fan found",
    "add.waitingWifi": "The device is waiting for Wi-Fi setup",
    "add.wifi": "2.4 GHz Wi-Fi network",
    "add.wifiPass": "Wi-Fi password",
    "add.wifiPassPh": "Stays on your device — this step is simulated",
    "add.connect": "Connect",
    "add.pairing": "Pairing with {wifi}",
    "add.pairingHint": "Make sure the Wi-Fi light on the fan is blinking.",
    "add.simulate": "Simulate a successful connection",
    "add.online": "Device is online",
    "add.name": "Device name",
    "add.room": "Room",
    "add.finish": "Finish",
    "add.done": "Device added",
    "add.ready": "{name} is ready to control.",
    "add.home": "Back to home",
    "add.defaultName": "New fan",
    "add.defaultHouse": "My home",
    "add.defaultRoom": "Living room",
    "add.defaultGroup": "Default",
    "add.tenTem": "Name on the label",
    "add.tenTemPh": "e.g. fan81029",
    "add.maSo": "5-digit claim code",
    "add.maSoPh": "5-digit code on the label",
    "add.moPhong": "The web version simulates this step — real Bluetooth pairing needs the mobile app.",
    "add.machPhaiOnline": "The board must be powered on and online.",
    "add.chuaOnline": "Board claimed but not seen online yet — check power and Wi-Fi.",
    "add.moCamera": "Open camera to scan",
    "add.dungQuet": "Stop scanning",
    "add.quetKhongDuoc": "Could not open the camera — check camera permission (the page must run on HTTPS), or type it in below.",
    "add.quetCanHttps": "The page is served over http://, so the browser blocks the camera — open it via https:// or localhost, or type it in below.",
    "add.daQuet": "Label code read.",
    "add.maWifi": "This is code ① (the board's Wi-Fi). Scan code ② “Add to Livotec” instead.",
    "add.quetThieuTen": "The code has no label name — type it in below.",
    "add.timBle": "Find device over Bluetooth",
    "add.daGhepNoi": "Paired with {ten}",
    "add.bleChon": "The browser will show a chooser — pick the device named “{ten}” (or PROV_…).",
    "add.bleKhongHoTro": "This browser has no Web Bluetooth (iPhone/iPad, Firefox) — pairing is simulated here; real pairing needs the mobile app.",
    "add.bleCanHttps": "The page is served over http://, so the browser disables Web Bluetooth — open it via https:// or localhost to pair for real; here this step is simulated.",
    "add.bleHuy": "No device selected.",
    "add.bleLoi": "Could not pair: {loi}",
    "add.boQuaBle": "Skip (simulate)",
    "add.wifiMoPhongSauBle": "Paired for real; sending Wi-Fi settings to the board is still simulated — waiting for the firmware's Security 2 spec.",
    "add.tiepTuc": "Continue",
  },
  fil: {
    "routine.previewFailed": "hindi ma-preview",
    "routine.and": "AT",
    "routine.or": "O",
    "common.delete": "Burahin",
    "routine.timeWindow": "Oras",
    "common.to": "hanggang",
    "routine.noDays": "Walang piniling araw = araw-araw",
    "routine.pickDevice": "Pumili ng device",
    "routine.pickCap": "Pumili ng sukat",
    "common.add": "Magdagdag",
    "common.back": "Bumalik",
    "routine.condTitle": "Automation na Kung–Kaya",
    "routine.title": "Automation",
    "routine.namePhCond": "Pangalan, hal. Mainit → buksan ang bentilador",
    "routine.if": "KUNG",
    "routine.allConds": "Dapat totoo lahat bago tumakbo.",
    "routine.onlyOpt": "KAPAG LANG (opsyonal)",
    "routine.onlyHint": "Pahintulot — dapat totoo lahat bago tumakbo.",
    "routine.exceptOpt": "MALIBAN KAPAG (opsyonal)",
    "routine.exceptHint": "Hadlang — isang totoo ay sapat para hindi tumakbo.",
    "routine.thenMax": "KAYA (hanggang 20)",
    "routine.doWhat": "Anong gagawin",
    "routine.actionN": "aksyon {n}",
    "routine.notifyDefault": "Katatakbo lang ng automation",
    "common.device": "device",
    "routine.sendNotify": "Magpadala ng abiso",
    "routine.notifyText": "Nilalaman ng abiso",
    "routine.waitSeconds": "maghintay (segundo)",
    "routine.validityFull": "BISA (blangko = ngayon at habambuhay)",
    "routine.expiryHint": "Kapag nag-expire, awtomatikong mag-o-off ang automation; hindi ito mabubura.",
    "routine.hold": "Dapat manatiling totoo ang kondisyon nang",
    "routine.holdNow": "agad-agad",
    "dur.30s": "30 segundo",
    "dur.1m": "1 minuto",
    "dur.5m": "5 minuto",
    "routine.yield": "Pagbigyan ang user",
    "routine.noYield": "huwag pagbigyan",
    "dur.15m": "15 minuto",
    "dur.1h": "1 oras",
    "routine.yieldHint": "Kapag ikaw mismo ang nag-adjust ng device, hindi ito gagalawin ng automation sa loob ng panahong ito.",
    "routine.preview": "Preview — tatakbo ba ngayon?",
    "routine.willRun": "Tatakbo ngayon",
    "routine.wontRun": "Hindi tatakbo — {why}",
    "routine.pass": "totoo",
    "routine.fail": "mali",
    "routine.currently": "ngayon {v}",
    "routine.shadowHint": "Laging nagsisimula sa shadow mode ang bagong automation: itinatala ng sistema ang “sana tumakbo” pero wala pang totoong utos.",
    "common.saving": "Sine-save…",
    "common.save": "I-save",
    "routine.value": "halaga",
    "routine.op": "operator",
    "routine.actionKind": "uri ng aksyon",
    "routine.startsAt": "simula",
    "routine.endsAt": "wakas",
    "common.on": "Bukas",
    "common.off": "Sarado",
    "virtual.external": "Panlabas na pinagmulan",
    "virtual.externalDesc": "Panahon, kalidad ng hangin",
    "virtual.phExternal": "Pangalan, hal. Panahon sa Hanoi",
    "virtual.state": "Kalagayan ng bahay",
    "virtual.stateDesc": "May tao sa bahay, sleep mode, wala sa bahay",
    "virtual.phState": "Pangalan, hal. May tao sa bahay",
    "virtual.button": "Pindutan",
    "virtual.buttonDesc": "Pag-uwi, pagtulog — isang pindot at tatakbo ang automation",
    "virtual.phButton": "Pangalan, hal. Matutulog na",
    "state.on": "Bukas",
    "state.offNow": "Sarado",
    "virtual.pressCount": "napindot nang {n} beses",
    "virtual.humidity": "halumigmig {v}%",
    "virtual.aqi": "hangin {v}",
    "virtual.noData": "wala pang datos — hinihintay ang unang kuha",
    "virtual.title": "Mga virtual na device",
    "virtual.hint": "Mga bagay na may pangalan at kalagayan pero hindi kagamitan sa bahay.",
    "virtual.mockNote": "Kailangan ng screen na ito ang IoTX server. Tumatakbo ang app sa mock mode kaya hindi pa makagawa ng virtual na device.",
    "common.create": "Gumawa",
    "place.title": "Lugar",
    "virtual.pickPlace": "Pumili ng lugar",
    "virtual.limit": "Hanggang 10 virtual na device. Hindi mabubura ang ginagamit ng automation.",
    "common.close": "Isara",
    "virtual.empty": "Wala pang virtual na device.",
    "virtual.press": "Pindutin",
    "share.viewOnly": "tingin lang",
    "share.controlOnly": "kontrol lang",
    "share.noDelete": "hindi makabura",
    "share.fullAccess": "buong access",
    "share.oneDevice": "isang device",
    "share.needEmailHouse": "Maglagay ng email at pumili ng bahay",
    "share.invited": "Naimbitahan — wala pang account ang taong ito at makakakuha ng access sa pag-sign up",
    "share.shared": "Naibahagi ✓",
    "share.inviteFailed": "Hindi maimbitahan — suriin ang email",
    "share.permsUpdated": "Na-update ang mga pahintulot",
    "share.revoked": "Tinanggal",
    "share.title": "Mga miyembro at pagbabahagi",
    "share.invite": "Mag-imbita ng miyembro",
    "share.noHouse": "Wala kang bahay na maibabahagi. Ang may-ari lang ng bahay ang makakapag-imbita — gumawa muna ng bahay sa Pamahalaan ang bahay / kuwarto / grupo.",
    "share.emailPh": "Email ng tatanggap",
    "share.scopeHouse": "Buong bahay",
    "share.scopeRoom": "Isang kuwarto",
    "share.scopeDevice": "Isang device",
    "share.pickHouse": "Pumili ng bahay",
    "share.pickRoom": "Pumili ng kuwarto",
    "share.defaultHint": "Bilang default, magagawa ng miyembro ang lahat ng kaya mo. Limitahan sa “Advanced”.",
    "share.advanced": "Advanced",
    "share.blockDelete": "Bawal magbura (puwede pa ring gumawa)",
    "common.working": "Kumokonekta…",
    "share.doShare": "Ibahagi",
    "share.sharedWith": "Ibinahagi kay",
    "share.noneShared": "Wala pang pinagbahaginan.",
    "share.pending": "naghihintay ng sign-up",
    "share.revokeConfirm": "Tanggalin ang access ng miyembrong ito?",
    "share.revoke": "Tanggalin ang access",
    "share.sharedToMe": "Ibinahagi sa akin",
    "share.noneToMe": "Wala pang nagbahagi sa iyo.",
    "routine.condN": "kondisyon {n}",
    "share.oneRoom": "kuwarto {name}",
    "share.wholeHouse": "buong bahay {name}",
    "op.eq": "katumbas ng",
    "op.neq": "hindi katumbas ng",
    "op.gt": "higit sa",
    "op.lt": "mas mababa sa",
    "dow.sun": "Li",
    "dow.mon": "Lu",
    "dow.tue": "Ma",
    "dow.wed": "Mi",
    "dow.thu": "Hu",
    "dow.fri": "Bi",
    "dow.sat": "Sa",
    notif_empty: "Wala pang abiso.",
    notif_clear: "Burahin lahat ng abiso",
    notif_delete: "Burahin ang abisong ito",
    club_kitchen: "Club ng Mahilig sa Kusina",
    club_aircon: "Club ng Aircon",
    club_water: "Club ng Water Purifier",
    club_fan: "Club ng Bentilador",
    promo_aircon: "Promo ng aircon na I-Boost",
    promo_wh: "Promo ng water heater",
    loc_nha: "Bahay",
    loc_phong: "Kuwarto",
    loc_nhom: "Grupo",
    splash_loading: "Sinisimulan ang Livotec Home…",
    toast_close: "Isara ang abiso",
    supplies_new: "Bagong suplay",
    banner_aircon: "Teknolohiyang i-Boost — aircon na I30J",
    banner_cooktop: "Dobleng induction cooktop na LIO-888VT",
    banner_water_title: "Water Purifier 886i",
    banner_water_sub: "Matalinong teknolohiyang I-Vision",
    "spaces.title": "Pamahalaan ang mga espasyo",
    "spaces.newPh": "Pangalan ng bagong {loai}",
    "spaces.syncNote": "Naka-sync ang mga espasyo sa iyong Livotec account.",
    "add.title": "Magdagdag ng device",
    "add.how": "Paano mo gustong idagdag ang device?",
    "add.qr": "I-scan ang QR code",
    "add.qrHint": "Pinakamabilis · nasa katawan ng device ang code",
    "add.serial": "Ilagay ang code ng device",
    "add.serialHint": "May Wi-Fi at sertipiko na ang board — kailangan lang ang serial sa katawan",
    "add.scanQr": "Ilagay ang QR code sa loob ng frame",
    "add.enterSerial": "Ilagay ang serial ng device",
    "add.code": "Code ng device",
    "add.identify": "Kilalanin ang device",
    "add.found": "Natagpuan ang bentilador na Livotec",
    "add.waitingWifi": "Naghihintay ang device ng Wi-Fi setup",
    "add.wifi": "Wi-Fi na 2.4 GHz",
    "add.wifiPass": "Password ng Wi-Fi",
    "add.wifiPassPh": "Nananatili sa iyong device — ginagaya lang ang hakbang na ito",
    "add.connect": "Kumonekta",
    "add.pairing": "Nagpa-pair sa {wifi}",
    "add.pairingHint": "Siguraduhing kumukurap ang ilaw ng Wi-Fi sa bentilador.",
    "add.simulate": "Gayahin ang matagumpay na koneksyon",
    "add.online": "Online na ang device",
    "add.name": "Pangalan ng device",
    "add.room": "Kuwarto",
    "add.finish": "Tapos",
    "add.done": "Naidagdag ang device",
    "add.ready": "Handa nang kontrolin ang {name}.",
    "add.home": "Bumalik sa home",
    "add.defaultName": "Bagong bentilador",
    "add.defaultHouse": "Bahay ko",
    "add.defaultRoom": "Sala",
    "add.defaultGroup": "Default",
    "add.tenTem": "Pangalan sa label",
    "add.tenTemPh": "hal. fan81029",
    "add.maSo": "5-digit na claim code",
    "add.maSoPh": "5-digit na code sa label",
    "add.moPhong": "Ginagaya ng web ang hakbang na ito — ang totoong Bluetooth pairing ay nangangailangan ng mobile app.",
    "add.machPhaiOnline": "Dapat nakasaksak at online ang board.",
    "add.chuaOnline": "Na-claim ang board pero hindi pa nakikitang online — suriin ang kuryente at Wi-Fi.",
    "add.moCamera": "Buksan ang camera para mag-scan",
    "add.dungQuet": "Itigil ang pag-scan",
    "add.quetKhongDuoc": "Hindi mabuksan ang camera — suriin ang pahintulot sa camera (dapat HTTPS ang pahina), o i-type sa ibaba.",
    "add.quetCanHttps": "Bukas ang pahina sa http://, kaya hinaharang ng browser ang camera — buksan sa https:// o localhost, o i-type sa ibaba.",
    "add.daQuet": "Nabasa ang code sa label.",
    "add.maWifi": "Ito ang code ① (Wi-Fi ng board). I-scan ang code ② “Idagdag sa Livotec”.",
    "add.quetThieuTen": "Walang pangalan ng label sa code — i-type sa ibaba.",
    "add.timBle": "Hanapin ang device sa Bluetooth",
    "add.daGhepNoi": "Naka-pair sa {ten}",
    "add.bleChon": "Magpapakita ang browser ng pagpipilian — piliin ang device na “{ten}” (o PROV_…).",
    "add.bleKhongHoTro": "Walang Web Bluetooth ang browser na ito (iPhone/iPad, Firefox) — ginagaya lang ang pairing dito; kailangan ng mobile app para sa totoo.",
    "add.bleCanHttps": "Bukas ang pahina sa http://, kaya naka-off ang Web Bluetooth — buksan sa https:// o localhost para sa totoong pairing; dito ginagaya lang ang hakbang na ito.",
    "add.bleHuy": "Walang napiling device.",
    "add.bleLoi": "Hindi maka-pair: {loi}",
    "add.boQuaBle": "Laktawan (gayahin)",
    "add.wifiMoPhongSauBle": "Totoong naka-pair; ginagaya pa rin ang pagpapadala ng Wi-Fi sa board — hinihintay ang Security 2 spec ng firmware.",
    "add.tiepTuc": "Magpatuloy",
  },
};
/**
 * Khóa mới ghi đè khóa cũ cùng tên, để bản vá chữ không phải sửa ba khối lớn phía trên.
 * Lúc phát triển, soát ba ngôn ngữ có cùng bộ khóa: thiếu khóa thì màn rơi về tiếng Việt
 * mà không ai hay (xem `chu.tsx`).
 */
export const CHU: Record<MaNgonNgu, Record<string, string>> = {
  vi: { ...vi, ...MOI.vi, ...PANEL.vi },
  en: { ...en, ...MOI.en, ...PANEL.en },
  fil: { ...fil, ...MOI.fil, ...PANEL.fil },
};
export function laMaNgonNgu(ma: string): ma is MaNgonNgu {
  return ma === "vi" || ma === "en" || ma === "fil";
}

if (process.env.NODE_ENV !== "production") {
  const khoaVi = new Set(Object.keys(CHU.vi));
  for (const ma of ["en", "fil"] as const) {
    const thieu = [...khoaVi].filter(k => !(k in CHU[ma]));
    if (thieu.length) console.warn(`[strings] ${ma} thiếu ${thieu.length} khóa so với vi:`, thieu.slice(0, 20));
  }
}
